// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticket"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticketcomment"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	ticketMixin := schema.Ticket{}.Mixin()
	ticket.Policy = privacy.NewPolicies(ticketMixin[2], schema.Ticket{})
	ticket.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := ticket.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	ticketMixinFields2 := ticketMixin[2].Fields()
	_ = ticketMixinFields2
	ticketFields := schema.Ticket{}.Fields()
	_ = ticketFields
	// ticketDescTenantID is the schema descriptor for tenant_id field.
	ticketDescTenantID := ticketMixinFields2[0].Descriptor()
	// ticket.DefaultTenantID holds the default value on creation for the tenant_id field.
	ticket.DefaultTenantID = ticketDescTenantID.Default.(uint32)
	// ticketDescSubject is the schema descriptor for subject field.
	ticketDescSubject := ticketFields[2].Descriptor()
	// ticket.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	ticket.SubjectValidator = ticketDescSubject.Validators[0].(func(string) error)
	// ticketDescStatus is the schema descriptor for status field.
	ticketDescStatus := ticketFields[4].Descriptor()
	// ticket.DefaultStatus holds the default value on creation for the status field.
	ticket.DefaultStatus = ticketDescStatus.Default.(string)
	// ticketDescPriority is the schema descriptor for priority field.
	ticketDescPriority := ticketFields[5].Descriptor()
	// ticket.DefaultPriority holds the default value on creation for the priority field.
	ticket.DefaultPriority = ticketDescPriority.Default.(string)
	// ticketDescSource is the schema descriptor for source field.
	ticketDescSource := ticketFields[6].Descriptor()
	// ticket.DefaultSource holds the default value on creation for the source field.
	ticket.DefaultSource = ticketDescSource.Default.(string)
	// ticketDescAssigneeID is the schema descriptor for assignee_id field.
	ticketDescAssigneeID := ticketFields[10].Descriptor()
	// ticket.DefaultAssigneeID holds the default value on creation for the assignee_id field.
	ticket.DefaultAssigneeID = ticketDescAssigneeID.Default.(uint32)
	// ticketDescID is the schema descriptor for id field.
	ticketDescID := ticketFields[0].Descriptor()
	// ticket.IDValidator is a validator for the "id" field. It is called by the builders before save.
	ticket.IDValidator = ticketDescID.Validators[0].(func(string) error)
	ticketcommentMixin := schema.TicketComment{}.Mixin()
	ticketcomment.Policy = privacy.NewPolicies(ticketcommentMixin[1], schema.TicketComment{})
	ticketcomment.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := ticketcomment.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	ticketcommentMixinFields1 := ticketcommentMixin[1].Fields()
	_ = ticketcommentMixinFields1
	ticketcommentFields := schema.TicketComment{}.Fields()
	_ = ticketcommentFields
	// ticketcommentDescTenantID is the schema descriptor for tenant_id field.
	ticketcommentDescTenantID := ticketcommentMixinFields1[0].Descriptor()
	// ticketcomment.DefaultTenantID holds the default value on creation for the tenant_id field.
	ticketcomment.DefaultTenantID = ticketcommentDescTenantID.Default.(uint32)
	// ticketcommentDescTicketID is the schema descriptor for ticket_id field.
	ticketcommentDescTicketID := ticketcommentFields[1].Descriptor()
	// ticketcomment.TicketIDValidator is a validator for the "ticket_id" field. It is called by the builders before save.
	ticketcomment.TicketIDValidator = ticketcommentDescTicketID.Validators[0].(func(string) error)
	// ticketcommentDescBody is the schema descriptor for body field.
	ticketcommentDescBody := ticketcommentFields[2].Descriptor()
	// ticketcomment.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	ticketcomment.BodyValidator = ticketcommentDescBody.Validators[0].(func(string) error)
	// ticketcommentDescInternal is the schema descriptor for internal field.
	ticketcommentDescInternal := ticketcommentFields[3].Descriptor()
	// ticketcomment.DefaultInternal holds the default value on creation for the internal field.
	ticketcomment.DefaultInternal = ticketcommentDescInternal.Default.(bool)
	// ticketcommentDescAuthorID is the schema descriptor for author_id field.
	ticketcommentDescAuthorID := ticketcommentFields[4].Descriptor()
	// ticketcomment.DefaultAuthorID holds the default value on creation for the author_id field.
	ticketcomment.DefaultAuthorID = ticketcommentDescAuthorID.Default.(uint32)
	// ticketcommentDescID is the schema descriptor for id field.
	ticketcommentDescID := ticketcommentFields[0].Descriptor()
	// ticketcomment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	ticketcomment.IDValidator = ticketcommentDescID.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
