// Code generated by ent, DO NOT EDIT.

package ticketrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldSortOrder, v))
}

// Match applies equality check predicate on the "match" field. It's identical to MatchEQ.
func Match(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldMatch, v))
}

// Conditions applies equality check predicate on the "conditions" field. It's identical to ConditionsEQ.
func Conditions(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldConditions, v))
}

// Expression applies equality check predicate on the "expression" field. It's identical to ExpressionEQ.
func Expression(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldExpression, v))
}

// TagKind applies equality check predicate on the "tag_kind" field. It's identical to TagKindEQ.
func TagKind(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldTagKind, v))
}

// TagNames applies equality check predicate on the "tag_names" field. It's identical to TagNamesEQ.
func TagNames(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldTagNames, v))
}

// Actions applies equality check predicate on the "actions" field. It's identical to ActionsEQ.
func Actions(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldActions, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotNull(FieldTenantID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldSortOrder, v))
}

// MatchEQ applies the EQ predicate on the "match" field.
func MatchEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldMatch, v))
}

// MatchNEQ applies the NEQ predicate on the "match" field.
func MatchNEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldMatch, v))
}

// MatchIn applies the In predicate on the "match" field.
func MatchIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldMatch, vs...))
}

// MatchNotIn applies the NotIn predicate on the "match" field.
func MatchNotIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldMatch, vs...))
}

// MatchGT applies the GT predicate on the "match" field.
func MatchGT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldMatch, v))
}

// MatchGTE applies the GTE predicate on the "match" field.
func MatchGTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldMatch, v))
}

// MatchLT applies the LT predicate on the "match" field.
func MatchLT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldMatch, v))
}

// MatchLTE applies the LTE predicate on the "match" field.
func MatchLTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldMatch, v))
}

// MatchContains applies the Contains predicate on the "match" field.
func MatchContains(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContains(FieldMatch, v))
}

// MatchHasPrefix applies the HasPrefix predicate on the "match" field.
func MatchHasPrefix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasPrefix(FieldMatch, v))
}

// MatchHasSuffix applies the HasSuffix predicate on the "match" field.
func MatchHasSuffix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasSuffix(FieldMatch, v))
}

// MatchEqualFold applies the EqualFold predicate on the "match" field.
func MatchEqualFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEqualFold(FieldMatch, v))
}

// MatchContainsFold applies the ContainsFold predicate on the "match" field.
func MatchContainsFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContainsFold(FieldMatch, v))
}

// ConditionsEQ applies the EQ predicate on the "conditions" field.
func ConditionsEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldConditions, v))
}

// ConditionsNEQ applies the NEQ predicate on the "conditions" field.
func ConditionsNEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldConditions, v))
}

// ConditionsIn applies the In predicate on the "conditions" field.
func ConditionsIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldConditions, vs...))
}

// ConditionsNotIn applies the NotIn predicate on the "conditions" field.
func ConditionsNotIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldConditions, vs...))
}

// ConditionsGT applies the GT predicate on the "conditions" field.
func ConditionsGT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldConditions, v))
}

// ConditionsGTE applies the GTE predicate on the "conditions" field.
func ConditionsGTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldConditions, v))
}

// ConditionsLT applies the LT predicate on the "conditions" field.
func ConditionsLT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldConditions, v))
}

// ConditionsLTE applies the LTE predicate on the "conditions" field.
func ConditionsLTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldConditions, v))
}

// ConditionsContains applies the Contains predicate on the "conditions" field.
func ConditionsContains(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContains(FieldConditions, v))
}

// ConditionsHasPrefix applies the HasPrefix predicate on the "conditions" field.
func ConditionsHasPrefix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasPrefix(FieldConditions, v))
}

// ConditionsHasSuffix applies the HasSuffix predicate on the "conditions" field.
func ConditionsHasSuffix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasSuffix(FieldConditions, v))
}

// ConditionsIsNil applies the IsNil predicate on the "conditions" field.
func ConditionsIsNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIsNull(FieldConditions))
}

// ConditionsNotNil applies the NotNil predicate on the "conditions" field.
func ConditionsNotNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotNull(FieldConditions))
}

// ConditionsEqualFold applies the EqualFold predicate on the "conditions" field.
func ConditionsEqualFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEqualFold(FieldConditions, v))
}

// ConditionsContainsFold applies the ContainsFold predicate on the "conditions" field.
func ConditionsContainsFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContainsFold(FieldConditions, v))
}

// ExpressionEQ applies the EQ predicate on the "expression" field.
func ExpressionEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldExpression, v))
}

// ExpressionNEQ applies the NEQ predicate on the "expression" field.
func ExpressionNEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldExpression, v))
}

// ExpressionIn applies the In predicate on the "expression" field.
func ExpressionIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldExpression, vs...))
}

// ExpressionNotIn applies the NotIn predicate on the "expression" field.
func ExpressionNotIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldExpression, vs...))
}

// ExpressionGT applies the GT predicate on the "expression" field.
func ExpressionGT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldExpression, v))
}

// ExpressionGTE applies the GTE predicate on the "expression" field.
func ExpressionGTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldExpression, v))
}

// ExpressionLT applies the LT predicate on the "expression" field.
func ExpressionLT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldExpression, v))
}

// ExpressionLTE applies the LTE predicate on the "expression" field.
func ExpressionLTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldExpression, v))
}

// ExpressionContains applies the Contains predicate on the "expression" field.
func ExpressionContains(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContains(FieldExpression, v))
}

// ExpressionHasPrefix applies the HasPrefix predicate on the "expression" field.
func ExpressionHasPrefix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasPrefix(FieldExpression, v))
}

// ExpressionHasSuffix applies the HasSuffix predicate on the "expression" field.
func ExpressionHasSuffix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasSuffix(FieldExpression, v))
}

// ExpressionIsNil applies the IsNil predicate on the "expression" field.
func ExpressionIsNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIsNull(FieldExpression))
}

// ExpressionNotNil applies the NotNil predicate on the "expression" field.
func ExpressionNotNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotNull(FieldExpression))
}

// ExpressionEqualFold applies the EqualFold predicate on the "expression" field.
func ExpressionEqualFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEqualFold(FieldExpression, v))
}

// ExpressionContainsFold applies the ContainsFold predicate on the "expression" field.
func ExpressionContainsFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContainsFold(FieldExpression, v))
}

// TagKindEQ applies the EQ predicate on the "tag_kind" field.
func TagKindEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldTagKind, v))
}

// TagKindNEQ applies the NEQ predicate on the "tag_kind" field.
func TagKindNEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldTagKind, v))
}

// TagKindIn applies the In predicate on the "tag_kind" field.
func TagKindIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldTagKind, vs...))
}

// TagKindNotIn applies the NotIn predicate on the "tag_kind" field.
func TagKindNotIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldTagKind, vs...))
}

// TagKindGT applies the GT predicate on the "tag_kind" field.
func TagKindGT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldTagKind, v))
}

// TagKindGTE applies the GTE predicate on the "tag_kind" field.
func TagKindGTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldTagKind, v))
}

// TagKindLT applies the LT predicate on the "tag_kind" field.
func TagKindLT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldTagKind, v))
}

// TagKindLTE applies the LTE predicate on the "tag_kind" field.
func TagKindLTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldTagKind, v))
}

// TagKindContains applies the Contains predicate on the "tag_kind" field.
func TagKindContains(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContains(FieldTagKind, v))
}

// TagKindHasPrefix applies the HasPrefix predicate on the "tag_kind" field.
func TagKindHasPrefix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasPrefix(FieldTagKind, v))
}

// TagKindHasSuffix applies the HasSuffix predicate on the "tag_kind" field.
func TagKindHasSuffix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasSuffix(FieldTagKind, v))
}

// TagKindEqualFold applies the EqualFold predicate on the "tag_kind" field.
func TagKindEqualFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEqualFold(FieldTagKind, v))
}

// TagKindContainsFold applies the ContainsFold predicate on the "tag_kind" field.
func TagKindContainsFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContainsFold(FieldTagKind, v))
}

// TagNamesEQ applies the EQ predicate on the "tag_names" field.
func TagNamesEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldTagNames, v))
}

// TagNamesNEQ applies the NEQ predicate on the "tag_names" field.
func TagNamesNEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldTagNames, v))
}

// TagNamesIn applies the In predicate on the "tag_names" field.
func TagNamesIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldTagNames, vs...))
}

// TagNamesNotIn applies the NotIn predicate on the "tag_names" field.
func TagNamesNotIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldTagNames, vs...))
}

// TagNamesGT applies the GT predicate on the "tag_names" field.
func TagNamesGT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldTagNames, v))
}

// TagNamesGTE applies the GTE predicate on the "tag_names" field.
func TagNamesGTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldTagNames, v))
}

// TagNamesLT applies the LT predicate on the "tag_names" field.
func TagNamesLT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldTagNames, v))
}

// TagNamesLTE applies the LTE predicate on the "tag_names" field.
func TagNamesLTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldTagNames, v))
}

// TagNamesContains applies the Contains predicate on the "tag_names" field.
func TagNamesContains(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContains(FieldTagNames, v))
}

// TagNamesHasPrefix applies the HasPrefix predicate on the "tag_names" field.
func TagNamesHasPrefix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasPrefix(FieldTagNames, v))
}

// TagNamesHasSuffix applies the HasSuffix predicate on the "tag_names" field.
func TagNamesHasSuffix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasSuffix(FieldTagNames, v))
}

// TagNamesIsNil applies the IsNil predicate on the "tag_names" field.
func TagNamesIsNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIsNull(FieldTagNames))
}

// TagNamesNotNil applies the NotNil predicate on the "tag_names" field.
func TagNamesNotNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotNull(FieldTagNames))
}

// TagNamesEqualFold applies the EqualFold predicate on the "tag_names" field.
func TagNamesEqualFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEqualFold(FieldTagNames, v))
}

// TagNamesContainsFold applies the ContainsFold predicate on the "tag_names" field.
func TagNamesContainsFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContainsFold(FieldTagNames, v))
}

// ActionsEQ applies the EQ predicate on the "actions" field.
func ActionsEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEQ(FieldActions, v))
}

// ActionsNEQ applies the NEQ predicate on the "actions" field.
func ActionsNEQ(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNEQ(FieldActions, v))
}

// ActionsIn applies the In predicate on the "actions" field.
func ActionsIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIn(FieldActions, vs...))
}

// ActionsNotIn applies the NotIn predicate on the "actions" field.
func ActionsNotIn(vs ...string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotIn(FieldActions, vs...))
}

// ActionsGT applies the GT predicate on the "actions" field.
func ActionsGT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGT(FieldActions, v))
}

// ActionsGTE applies the GTE predicate on the "actions" field.
func ActionsGTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldGTE(FieldActions, v))
}

// ActionsLT applies the LT predicate on the "actions" field.
func ActionsLT(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLT(FieldActions, v))
}

// ActionsLTE applies the LTE predicate on the "actions" field.
func ActionsLTE(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldLTE(FieldActions, v))
}

// ActionsContains applies the Contains predicate on the "actions" field.
func ActionsContains(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContains(FieldActions, v))
}

// ActionsHasPrefix applies the HasPrefix predicate on the "actions" field.
func ActionsHasPrefix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasPrefix(FieldActions, v))
}

// ActionsHasSuffix applies the HasSuffix predicate on the "actions" field.
func ActionsHasSuffix(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldHasSuffix(FieldActions, v))
}

// ActionsIsNil applies the IsNil predicate on the "actions" field.
func ActionsIsNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldIsNull(FieldActions))
}

// ActionsNotNil applies the NotNil predicate on the "actions" field.
func ActionsNotNil() predicate.TicketRule {
	return predicate.TicketRule(sql.FieldNotNull(FieldActions))
}

// ActionsEqualFold applies the EqualFold predicate on the "actions" field.
func ActionsEqualFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldEqualFold(FieldActions, v))
}

// ActionsContainsFold applies the ContainsFold predicate on the "actions" field.
func ActionsContainsFold(v string) predicate.TicketRule {
	return predicate.TicketRule(sql.FieldContainsFold(FieldActions, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketRule) predicate.TicketRule {
	return predicate.TicketRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketRule) predicate.TicketRule {
	return predicate.TicketRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketRule) predicate.TicketRule {
	return predicate.TicketRule(sql.NotPredicates(p))
}
