// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticket"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticketcomment"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTicket        = "Ticket"
	TypeTicketComment = "TicketComment"
)

// TicketMutation represents an operation that mutates the Ticket nodes in the graph.
type TicketMutation struct {
	config
	op              Op
	typ             string
	id              *string
	create_by       *uint32
	addcreate_by    *int32
	create_time     *time.Time
	update_time     *time.Time
	delete_time     *time.Time
	tenant_id       *uint32
	addtenant_id    *int32
	external_id     *string
	subject         *string
	description     *string
	body_html       *string
	status          *string
	priority        *string
	source          *string
	requester_email *string
	requester_name  *string
	recipient       *string
	assignee_id     *uint32
	addassignee_id  *int32
	clearedFields   map[string]struct{}
	comments        map[string]struct{}
	removedcomments map[string]struct{}
	clearedcomments bool
	done            bool
	oldValue        func(context.Context) (*Ticket, error)
	predicates      []predicate.Ticket
}

var _ ent.Mutation = (*TicketMutation)(nil)

// ticketOption allows management of the mutation configuration using functional options.
type ticketOption func(*TicketMutation)

// newTicketMutation creates new mutation for the Ticket entity.
func newTicketMutation(c config, op Op, opts ...ticketOption) *TicketMutation {
	m := &TicketMutation{
		config:        c,
		op:            op,
		typ:           TypeTicket,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTicketID sets the ID field of the mutation.
func withTicketID(id string) ticketOption {
	return func(m *TicketMutation) {
		var (
			err   error
			once  sync.Once
			value *Ticket
		)
		m.oldValue = func(ctx context.Context) (*Ticket, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Ticket.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTicket sets the old Ticket of the mutation.
func withTicket(node *Ticket) ticketOption {
	return func(m *TicketMutation) {
		m.oldValue = func(context.Context) (*Ticket, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TicketMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TicketMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Ticket entities.
func (m *TicketMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TicketMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TicketMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Ticket.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateBy sets the "create_by" field.
func (m *TicketMutation) SetCreateBy(u uint32) {
	m.create_by = &u
	m.addcreate_by = nil
}

// CreateBy returns the value of the "create_by" field in the mutation.
func (m *TicketMutation) CreateBy() (r uint32, exists bool) {
	v := m.create_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateBy returns the old "create_by" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldCreateBy(ctx context.Context) (v *uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateBy: %w", err)
	}
	return oldValue.CreateBy, nil
}

// AddCreateBy adds u to the "create_by" field.
func (m *TicketMutation) AddCreateBy(u int32) {
	if m.addcreate_by != nil {
		*m.addcreate_by += u
	} else {
		m.addcreate_by = &u
	}
}

// AddedCreateBy returns the value that was added to the "create_by" field in this mutation.
func (m *TicketMutation) AddedCreateBy() (r int32, exists bool) {
	v := m.addcreate_by
	if v == nil {
		return
	}
	return *v, true
}

// ClearCreateBy clears the value of the "create_by" field.
func (m *TicketMutation) ClearCreateBy() {
	m.create_by = nil
	m.addcreate_by = nil
	m.clearedFields[ticket.FieldCreateBy] = struct{}{}
}

// CreateByCleared returns if the "create_by" field was cleared in this mutation.
func (m *TicketMutation) CreateByCleared() bool {
	_, ok := m.clearedFields[ticket.FieldCreateBy]
	return ok
}

// ResetCreateBy resets all changes to the "create_by" field.
func (m *TicketMutation) ResetCreateBy() {
	m.create_by = nil
	m.addcreate_by = nil
	delete(m.clearedFields, ticket.FieldCreateBy)
}

// SetCreateTime sets the "create_time" field.
func (m *TicketMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *TicketMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldCreateTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ClearCreateTime clears the value of the "create_time" field.
func (m *TicketMutation) ClearCreateTime() {
	m.create_time = nil
	m.clearedFields[ticket.FieldCreateTime] = struct{}{}
}

// CreateTimeCleared returns if the "create_time" field was cleared in this mutation.
func (m *TicketMutation) CreateTimeCleared() bool {
	_, ok := m.clearedFields[ticket.FieldCreateTime]
	return ok
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *TicketMutation) ResetCreateTime() {
	m.create_time = nil
	delete(m.clearedFields, ticket.FieldCreateTime)
}

// SetUpdateTime sets the "update_time" field.
func (m *TicketMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *TicketMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldUpdateTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ClearUpdateTime clears the value of the "update_time" field.
func (m *TicketMutation) ClearUpdateTime() {
	m.update_time = nil
	m.clearedFields[ticket.FieldUpdateTime] = struct{}{}
}

// UpdateTimeCleared returns if the "update_time" field was cleared in this mutation.
func (m *TicketMutation) UpdateTimeCleared() bool {
	_, ok := m.clearedFields[ticket.FieldUpdateTime]
	return ok
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *TicketMutation) ResetUpdateTime() {
	m.update_time = nil
	delete(m.clearedFields, ticket.FieldUpdateTime)
}

// SetDeleteTime sets the "delete_time" field.
func (m *TicketMutation) SetDeleteTime(t time.Time) {
	m.delete_time = &t
}

// DeleteTime returns the value of the "delete_time" field in the mutation.
func (m *TicketMutation) DeleteTime() (r time.Time, exists bool) {
	v := m.delete_time
	if v == nil {
		return
	}
	return *v, true
}

// OldDeleteTime returns the old "delete_time" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldDeleteTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeleteTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeleteTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeleteTime: %w", err)
	}
	return oldValue.DeleteTime, nil
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (m *TicketMutation) ClearDeleteTime() {
	m.delete_time = nil
	m.clearedFields[ticket.FieldDeleteTime] = struct{}{}
}

// DeleteTimeCleared returns if the "delete_time" field was cleared in this mutation.
func (m *TicketMutation) DeleteTimeCleared() bool {
	_, ok := m.clearedFields[ticket.FieldDeleteTime]
	return ok
}

// ResetDeleteTime resets all changes to the "delete_time" field.
func (m *TicketMutation) ResetDeleteTime() {
	m.delete_time = nil
	delete(m.clearedFields, ticket.FieldDeleteTime)
}

// SetTenantID sets the "tenant_id" field.
func (m *TicketMutation) SetTenantID(u uint32) {
	m.tenant_id = &u
	m.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *TicketMutation) TenantID() (r uint32, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldTenantID(ctx context.Context) (v *uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds u to the "tenant_id" field.
func (m *TicketMutation) AddTenantID(u int32) {
	if m.addtenant_id != nil {
		*m.addtenant_id += u
	} else {
		m.addtenant_id = &u
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (m *TicketMutation) AddedTenantID() (r int32, exists bool) {
	v := m.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearTenantID clears the value of the "tenant_id" field.
func (m *TicketMutation) ClearTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
	m.clearedFields[ticket.FieldTenantID] = struct{}{}
}

// TenantIDCleared returns if the "tenant_id" field was cleared in this mutation.
func (m *TicketMutation) TenantIDCleared() bool {
	_, ok := m.clearedFields[ticket.FieldTenantID]
	return ok
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *TicketMutation) ResetTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
	delete(m.clearedFields, ticket.FieldTenantID)
}

// SetExternalID sets the "external_id" field.
func (m *TicketMutation) SetExternalID(s string) {
	m.external_id = &s
}

// ExternalID returns the value of the "external_id" field in the mutation.
func (m *TicketMutation) ExternalID() (r string, exists bool) {
	v := m.external_id
	if v == nil {
		return
	}
	return *v, true
}

// OldExternalID returns the old "external_id" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldExternalID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExternalID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExternalID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExternalID: %w", err)
	}
	return oldValue.ExternalID, nil
}

// ClearExternalID clears the value of the "external_id" field.
func (m *TicketMutation) ClearExternalID() {
	m.external_id = nil
	m.clearedFields[ticket.FieldExternalID] = struct{}{}
}

// ExternalIDCleared returns if the "external_id" field was cleared in this mutation.
func (m *TicketMutation) ExternalIDCleared() bool {
	_, ok := m.clearedFields[ticket.FieldExternalID]
	return ok
}

// ResetExternalID resets all changes to the "external_id" field.
func (m *TicketMutation) ResetExternalID() {
	m.external_id = nil
	delete(m.clearedFields, ticket.FieldExternalID)
}

// SetSubject sets the "subject" field.
func (m *TicketMutation) SetSubject(s string) {
	m.subject = &s
}

// Subject returns the value of the "subject" field in the mutation.
func (m *TicketMutation) Subject() (r string, exists bool) {
	v := m.subject
	if v == nil {
		return
	}
	return *v, true
}

// OldSubject returns the old "subject" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldSubject(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubject is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubject requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubject: %w", err)
	}
	return oldValue.Subject, nil
}

// ResetSubject resets all changes to the "subject" field.
func (m *TicketMutation) ResetSubject() {
	m.subject = nil
}

// SetDescription sets the "description" field.
func (m *TicketMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *TicketMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *TicketMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[ticket.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *TicketMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[ticket.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *TicketMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, ticket.FieldDescription)
}

// SetBodyHTML sets the "body_html" field.
func (m *TicketMutation) SetBodyHTML(s string) {
	m.body_html = &s
}

// BodyHTML returns the value of the "body_html" field in the mutation.
func (m *TicketMutation) BodyHTML() (r string, exists bool) {
	v := m.body_html
	if v == nil {
		return
	}
	return *v, true
}

// OldBodyHTML returns the old "body_html" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldBodyHTML(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBodyHTML is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBodyHTML requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBodyHTML: %w", err)
	}
	return oldValue.BodyHTML, nil
}

// ClearBodyHTML clears the value of the "body_html" field.
func (m *TicketMutation) ClearBodyHTML() {
	m.body_html = nil
	m.clearedFields[ticket.FieldBodyHTML] = struct{}{}
}

// BodyHTMLCleared returns if the "body_html" field was cleared in this mutation.
func (m *TicketMutation) BodyHTMLCleared() bool {
	_, ok := m.clearedFields[ticket.FieldBodyHTML]
	return ok
}

// ResetBodyHTML resets all changes to the "body_html" field.
func (m *TicketMutation) ResetBodyHTML() {
	m.body_html = nil
	delete(m.clearedFields, ticket.FieldBodyHTML)
}

// SetStatus sets the "status" field.
func (m *TicketMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *TicketMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *TicketMutation) ResetStatus() {
	m.status = nil
}

// SetPriority sets the "priority" field.
func (m *TicketMutation) SetPriority(s string) {
	m.priority = &s
}

// Priority returns the value of the "priority" field in the mutation.
func (m *TicketMutation) Priority() (r string, exists bool) {
	v := m.priority
	if v == nil {
		return
	}
	return *v, true
}

// OldPriority returns the old "priority" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldPriority(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPriority is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPriority requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPriority: %w", err)
	}
	return oldValue.Priority, nil
}

// ResetPriority resets all changes to the "priority" field.
func (m *TicketMutation) ResetPriority() {
	m.priority = nil
}

// SetSource sets the "source" field.
func (m *TicketMutation) SetSource(s string) {
	m.source = &s
}

// Source returns the value of the "source" field in the mutation.
func (m *TicketMutation) Source() (r string, exists bool) {
	v := m.source
	if v == nil {
		return
	}
	return *v, true
}

// OldSource returns the old "source" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldSource(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSource is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSource requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSource: %w", err)
	}
	return oldValue.Source, nil
}

// ResetSource resets all changes to the "source" field.
func (m *TicketMutation) ResetSource() {
	m.source = nil
}

// SetRequesterEmail sets the "requester_email" field.
func (m *TicketMutation) SetRequesterEmail(s string) {
	m.requester_email = &s
}

// RequesterEmail returns the value of the "requester_email" field in the mutation.
func (m *TicketMutation) RequesterEmail() (r string, exists bool) {
	v := m.requester_email
	if v == nil {
		return
	}
	return *v, true
}

// OldRequesterEmail returns the old "requester_email" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldRequesterEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequesterEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequesterEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequesterEmail: %w", err)
	}
	return oldValue.RequesterEmail, nil
}

// ClearRequesterEmail clears the value of the "requester_email" field.
func (m *TicketMutation) ClearRequesterEmail() {
	m.requester_email = nil
	m.clearedFields[ticket.FieldRequesterEmail] = struct{}{}
}

// RequesterEmailCleared returns if the "requester_email" field was cleared in this mutation.
func (m *TicketMutation) RequesterEmailCleared() bool {
	_, ok := m.clearedFields[ticket.FieldRequesterEmail]
	return ok
}

// ResetRequesterEmail resets all changes to the "requester_email" field.
func (m *TicketMutation) ResetRequesterEmail() {
	m.requester_email = nil
	delete(m.clearedFields, ticket.FieldRequesterEmail)
}

// SetRequesterName sets the "requester_name" field.
func (m *TicketMutation) SetRequesterName(s string) {
	m.requester_name = &s
}

// RequesterName returns the value of the "requester_name" field in the mutation.
func (m *TicketMutation) RequesterName() (r string, exists bool) {
	v := m.requester_name
	if v == nil {
		return
	}
	return *v, true
}

// OldRequesterName returns the old "requester_name" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldRequesterName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequesterName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequesterName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequesterName: %w", err)
	}
	return oldValue.RequesterName, nil
}

// ClearRequesterName clears the value of the "requester_name" field.
func (m *TicketMutation) ClearRequesterName() {
	m.requester_name = nil
	m.clearedFields[ticket.FieldRequesterName] = struct{}{}
}

// RequesterNameCleared returns if the "requester_name" field was cleared in this mutation.
func (m *TicketMutation) RequesterNameCleared() bool {
	_, ok := m.clearedFields[ticket.FieldRequesterName]
	return ok
}

// ResetRequesterName resets all changes to the "requester_name" field.
func (m *TicketMutation) ResetRequesterName() {
	m.requester_name = nil
	delete(m.clearedFields, ticket.FieldRequesterName)
}

// SetRecipient sets the "recipient" field.
func (m *TicketMutation) SetRecipient(s string) {
	m.recipient = &s
}

// Recipient returns the value of the "recipient" field in the mutation.
func (m *TicketMutation) Recipient() (r string, exists bool) {
	v := m.recipient
	if v == nil {
		return
	}
	return *v, true
}

// OldRecipient returns the old "recipient" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldRecipient(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRecipient is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRecipient requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRecipient: %w", err)
	}
	return oldValue.Recipient, nil
}

// ClearRecipient clears the value of the "recipient" field.
func (m *TicketMutation) ClearRecipient() {
	m.recipient = nil
	m.clearedFields[ticket.FieldRecipient] = struct{}{}
}

// RecipientCleared returns if the "recipient" field was cleared in this mutation.
func (m *TicketMutation) RecipientCleared() bool {
	_, ok := m.clearedFields[ticket.FieldRecipient]
	return ok
}

// ResetRecipient resets all changes to the "recipient" field.
func (m *TicketMutation) ResetRecipient() {
	m.recipient = nil
	delete(m.clearedFields, ticket.FieldRecipient)
}

// SetAssigneeID sets the "assignee_id" field.
func (m *TicketMutation) SetAssigneeID(u uint32) {
	m.assignee_id = &u
	m.addassignee_id = nil
}

// AssigneeID returns the value of the "assignee_id" field in the mutation.
func (m *TicketMutation) AssigneeID() (r uint32, exists bool) {
	v := m.assignee_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAssigneeID returns the old "assignee_id" field's value of the Ticket entity.
// If the Ticket object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketMutation) OldAssigneeID(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAssigneeID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAssigneeID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAssigneeID: %w", err)
	}
	return oldValue.AssigneeID, nil
}

// AddAssigneeID adds u to the "assignee_id" field.
func (m *TicketMutation) AddAssigneeID(u int32) {
	if m.addassignee_id != nil {
		*m.addassignee_id += u
	} else {
		m.addassignee_id = &u
	}
}

// AddedAssigneeID returns the value that was added to the "assignee_id" field in this mutation.
func (m *TicketMutation) AddedAssigneeID() (r int32, exists bool) {
	v := m.addassignee_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetAssigneeID resets all changes to the "assignee_id" field.
func (m *TicketMutation) ResetAssigneeID() {
	m.assignee_id = nil
	m.addassignee_id = nil
}

// AddCommentIDs adds the "comments" edge to the TicketComment entity by ids.
func (m *TicketMutation) AddCommentIDs(ids ...string) {
	if m.comments == nil {
		m.comments = make(map[string]struct{})
	}
	for i := range ids {
		m.comments[ids[i]] = struct{}{}
	}
}

// ClearComments clears the "comments" edge to the TicketComment entity.
func (m *TicketMutation) ClearComments() {
	m.clearedcomments = true
}

// CommentsCleared reports if the "comments" edge to the TicketComment entity was cleared.
func (m *TicketMutation) CommentsCleared() bool {
	return m.clearedcomments
}

// RemoveCommentIDs removes the "comments" edge to the TicketComment entity by IDs.
func (m *TicketMutation) RemoveCommentIDs(ids ...string) {
	if m.removedcomments == nil {
		m.removedcomments = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.comments, ids[i])
		m.removedcomments[ids[i]] = struct{}{}
	}
}

// RemovedComments returns the removed IDs of the "comments" edge to the TicketComment entity.
func (m *TicketMutation) RemovedCommentsIDs() (ids []string) {
	for id := range m.removedcomments {
		ids = append(ids, id)
	}
	return
}

// CommentsIDs returns the "comments" edge IDs in the mutation.
func (m *TicketMutation) CommentsIDs() (ids []string) {
	for id := range m.comments {
		ids = append(ids, id)
	}
	return
}

// ResetComments resets all changes to the "comments" edge.
func (m *TicketMutation) ResetComments() {
	m.comments = nil
	m.clearedcomments = false
	m.removedcomments = nil
}

// Where appends a list predicates to the TicketMutation builder.
func (m *TicketMutation) Where(ps ...predicate.Ticket) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TicketMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TicketMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Ticket, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TicketMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TicketMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Ticket).
func (m *TicketMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TicketMutation) Fields() []string {
	fields := make([]string, 0, 16)
	if m.create_by != nil {
		fields = append(fields, ticket.FieldCreateBy)
	}
	if m.create_time != nil {
		fields = append(fields, ticket.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, ticket.FieldUpdateTime)
	}
	if m.delete_time != nil {
		fields = append(fields, ticket.FieldDeleteTime)
	}
	if m.tenant_id != nil {
		fields = append(fields, ticket.FieldTenantID)
	}
	if m.external_id != nil {
		fields = append(fields, ticket.FieldExternalID)
	}
	if m.subject != nil {
		fields = append(fields, ticket.FieldSubject)
	}
	if m.description != nil {
		fields = append(fields, ticket.FieldDescription)
	}
	if m.body_html != nil {
		fields = append(fields, ticket.FieldBodyHTML)
	}
	if m.status != nil {
		fields = append(fields, ticket.FieldStatus)
	}
	if m.priority != nil {
		fields = append(fields, ticket.FieldPriority)
	}
	if m.source != nil {
		fields = append(fields, ticket.FieldSource)
	}
	if m.requester_email != nil {
		fields = append(fields, ticket.FieldRequesterEmail)
	}
	if m.requester_name != nil {
		fields = append(fields, ticket.FieldRequesterName)
	}
	if m.recipient != nil {
		fields = append(fields, ticket.FieldRecipient)
	}
	if m.assignee_id != nil {
		fields = append(fields, ticket.FieldAssigneeID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TicketMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case ticket.FieldCreateBy:
		return m.CreateBy()
	case ticket.FieldCreateTime:
		return m.CreateTime()
	case ticket.FieldUpdateTime:
		return m.UpdateTime()
	case ticket.FieldDeleteTime:
		return m.DeleteTime()
	case ticket.FieldTenantID:
		return m.TenantID()
	case ticket.FieldExternalID:
		return m.ExternalID()
	case ticket.FieldSubject:
		return m.Subject()
	case ticket.FieldDescription:
		return m.Description()
	case ticket.FieldBodyHTML:
		return m.BodyHTML()
	case ticket.FieldStatus:
		return m.Status()
	case ticket.FieldPriority:
		return m.Priority()
	case ticket.FieldSource:
		return m.Source()
	case ticket.FieldRequesterEmail:
		return m.RequesterEmail()
	case ticket.FieldRequesterName:
		return m.RequesterName()
	case ticket.FieldRecipient:
		return m.Recipient()
	case ticket.FieldAssigneeID:
		return m.AssigneeID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TicketMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case ticket.FieldCreateBy:
		return m.OldCreateBy(ctx)
	case ticket.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case ticket.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case ticket.FieldDeleteTime:
		return m.OldDeleteTime(ctx)
	case ticket.FieldTenantID:
		return m.OldTenantID(ctx)
	case ticket.FieldExternalID:
		return m.OldExternalID(ctx)
	case ticket.FieldSubject:
		return m.OldSubject(ctx)
	case ticket.FieldDescription:
		return m.OldDescription(ctx)
	case ticket.FieldBodyHTML:
		return m.OldBodyHTML(ctx)
	case ticket.FieldStatus:
		return m.OldStatus(ctx)
	case ticket.FieldPriority:
		return m.OldPriority(ctx)
	case ticket.FieldSource:
		return m.OldSource(ctx)
	case ticket.FieldRequesterEmail:
		return m.OldRequesterEmail(ctx)
	case ticket.FieldRequesterName:
		return m.OldRequesterName(ctx)
	case ticket.FieldRecipient:
		return m.OldRecipient(ctx)
	case ticket.FieldAssigneeID:
		return m.OldAssigneeID(ctx)
	}
	return nil, fmt.Errorf("unknown Ticket field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TicketMutation) SetField(name string, value ent.Value) error {
	switch name {
	case ticket.FieldCreateBy:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateBy(v)
		return nil
	case ticket.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case ticket.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case ticket.FieldDeleteTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeleteTime(v)
		return nil
	case ticket.FieldTenantID:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case ticket.FieldExternalID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExternalID(v)
		return nil
	case ticket.FieldSubject:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubject(v)
		return nil
	case ticket.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case ticket.FieldBodyHTML:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBodyHTML(v)
		return nil
	case ticket.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case ticket.FieldPriority:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPriority(v)
		return nil
	case ticket.FieldSource:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSource(v)
		return nil
	case ticket.FieldRequesterEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequesterEmail(v)
		return nil
	case ticket.FieldRequesterName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequesterName(v)
		return nil
	case ticket.FieldRecipient:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRecipient(v)
		return nil
	case ticket.FieldAssigneeID:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAssigneeID(v)
		return nil
	}
	return fmt.Errorf("unknown Ticket field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TicketMutation) AddedFields() []string {
	var fields []string
	if m.addcreate_by != nil {
		fields = append(fields, ticket.FieldCreateBy)
	}
	if m.addtenant_id != nil {
		fields = append(fields, ticket.FieldTenantID)
	}
	if m.addassignee_id != nil {
		fields = append(fields, ticket.FieldAssigneeID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TicketMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case ticket.FieldCreateBy:
		return m.AddedCreateBy()
	case ticket.FieldTenantID:
		return m.AddedTenantID()
	case ticket.FieldAssigneeID:
		return m.AddedAssigneeID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TicketMutation) AddField(name string, value ent.Value) error {
	switch name {
	case ticket.FieldCreateBy:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreateBy(v)
		return nil
	case ticket.FieldTenantID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTenantID(v)
		return nil
	case ticket.FieldAssigneeID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAssigneeID(v)
		return nil
	}
	return fmt.Errorf("unknown Ticket numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TicketMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(ticket.FieldCreateBy) {
		fields = append(fields, ticket.FieldCreateBy)
	}
	if m.FieldCleared(ticket.FieldCreateTime) {
		fields = append(fields, ticket.FieldCreateTime)
	}
	if m.FieldCleared(ticket.FieldUpdateTime) {
		fields = append(fields, ticket.FieldUpdateTime)
	}
	if m.FieldCleared(ticket.FieldDeleteTime) {
		fields = append(fields, ticket.FieldDeleteTime)
	}
	if m.FieldCleared(ticket.FieldTenantID) {
		fields = append(fields, ticket.FieldTenantID)
	}
	if m.FieldCleared(ticket.FieldExternalID) {
		fields = append(fields, ticket.FieldExternalID)
	}
	if m.FieldCleared(ticket.FieldDescription) {
		fields = append(fields, ticket.FieldDescription)
	}
	if m.FieldCleared(ticket.FieldBodyHTML) {
		fields = append(fields, ticket.FieldBodyHTML)
	}
	if m.FieldCleared(ticket.FieldRequesterEmail) {
		fields = append(fields, ticket.FieldRequesterEmail)
	}
	if m.FieldCleared(ticket.FieldRequesterName) {
		fields = append(fields, ticket.FieldRequesterName)
	}
	if m.FieldCleared(ticket.FieldRecipient) {
		fields = append(fields, ticket.FieldRecipient)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TicketMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TicketMutation) ClearField(name string) error {
	switch name {
	case ticket.FieldCreateBy:
		m.ClearCreateBy()
		return nil
	case ticket.FieldCreateTime:
		m.ClearCreateTime()
		return nil
	case ticket.FieldUpdateTime:
		m.ClearUpdateTime()
		return nil
	case ticket.FieldDeleteTime:
		m.ClearDeleteTime()
		return nil
	case ticket.FieldTenantID:
		m.ClearTenantID()
		return nil
	case ticket.FieldExternalID:
		m.ClearExternalID()
		return nil
	case ticket.FieldDescription:
		m.ClearDescription()
		return nil
	case ticket.FieldBodyHTML:
		m.ClearBodyHTML()
		return nil
	case ticket.FieldRequesterEmail:
		m.ClearRequesterEmail()
		return nil
	case ticket.FieldRequesterName:
		m.ClearRequesterName()
		return nil
	case ticket.FieldRecipient:
		m.ClearRecipient()
		return nil
	}
	return fmt.Errorf("unknown Ticket nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TicketMutation) ResetField(name string) error {
	switch name {
	case ticket.FieldCreateBy:
		m.ResetCreateBy()
		return nil
	case ticket.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case ticket.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case ticket.FieldDeleteTime:
		m.ResetDeleteTime()
		return nil
	case ticket.FieldTenantID:
		m.ResetTenantID()
		return nil
	case ticket.FieldExternalID:
		m.ResetExternalID()
		return nil
	case ticket.FieldSubject:
		m.ResetSubject()
		return nil
	case ticket.FieldDescription:
		m.ResetDescription()
		return nil
	case ticket.FieldBodyHTML:
		m.ResetBodyHTML()
		return nil
	case ticket.FieldStatus:
		m.ResetStatus()
		return nil
	case ticket.FieldPriority:
		m.ResetPriority()
		return nil
	case ticket.FieldSource:
		m.ResetSource()
		return nil
	case ticket.FieldRequesterEmail:
		m.ResetRequesterEmail()
		return nil
	case ticket.FieldRequesterName:
		m.ResetRequesterName()
		return nil
	case ticket.FieldRecipient:
		m.ResetRecipient()
		return nil
	case ticket.FieldAssigneeID:
		m.ResetAssigneeID()
		return nil
	}
	return fmt.Errorf("unknown Ticket field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TicketMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.comments != nil {
		edges = append(edges, ticket.EdgeComments)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TicketMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case ticket.EdgeComments:
		ids := make([]ent.Value, 0, len(m.comments))
		for id := range m.comments {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TicketMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedcomments != nil {
		edges = append(edges, ticket.EdgeComments)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TicketMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case ticket.EdgeComments:
		ids := make([]ent.Value, 0, len(m.removedcomments))
		for id := range m.removedcomments {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TicketMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedcomments {
		edges = append(edges, ticket.EdgeComments)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TicketMutation) EdgeCleared(name string) bool {
	switch name {
	case ticket.EdgeComments:
		return m.clearedcomments
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TicketMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Ticket unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TicketMutation) ResetEdge(name string) error {
	switch name {
	case ticket.EdgeComments:
		m.ResetComments()
		return nil
	}
	return fmt.Errorf("unknown Ticket edge %s", name)
}

// TicketCommentMutation represents an operation that mutates the TicketComment nodes in the graph.
type TicketCommentMutation struct {
	config
	op            Op
	typ           string
	id            *string
	create_time   *time.Time
	update_time   *time.Time
	delete_time   *time.Time
	tenant_id     *uint32
	addtenant_id  *int32
	body          *string
	internal      *bool
	author_id     *uint32
	addauthor_id  *int32
	author_email  *string
	clearedFields map[string]struct{}
	ticket        *string
	clearedticket bool
	done          bool
	oldValue      func(context.Context) (*TicketComment, error)
	predicates    []predicate.TicketComment
}

var _ ent.Mutation = (*TicketCommentMutation)(nil)

// ticketcommentOption allows management of the mutation configuration using functional options.
type ticketcommentOption func(*TicketCommentMutation)

// newTicketCommentMutation creates new mutation for the TicketComment entity.
func newTicketCommentMutation(c config, op Op, opts ...ticketcommentOption) *TicketCommentMutation {
	m := &TicketCommentMutation{
		config:        c,
		op:            op,
		typ:           TypeTicketComment,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTicketCommentID sets the ID field of the mutation.
func withTicketCommentID(id string) ticketcommentOption {
	return func(m *TicketCommentMutation) {
		var (
			err   error
			once  sync.Once
			value *TicketComment
		)
		m.oldValue = func(ctx context.Context) (*TicketComment, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TicketComment.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTicketComment sets the old TicketComment of the mutation.
func withTicketComment(node *TicketComment) ticketcommentOption {
	return func(m *TicketCommentMutation) {
		m.oldValue = func(context.Context) (*TicketComment, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TicketCommentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TicketCommentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of TicketComment entities.
func (m *TicketCommentMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TicketCommentMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TicketCommentMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TicketComment.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreateTime sets the "create_time" field.
func (m *TicketCommentMutation) SetCreateTime(t time.Time) {
	m.create_time = &t
}

// CreateTime returns the value of the "create_time" field in the mutation.
func (m *TicketCommentMutation) CreateTime() (r time.Time, exists bool) {
	v := m.create_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateTime returns the old "create_time" field's value of the TicketComment entity.
// If the TicketComment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketCommentMutation) OldCreateTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateTime: %w", err)
	}
	return oldValue.CreateTime, nil
}

// ClearCreateTime clears the value of the "create_time" field.
func (m *TicketCommentMutation) ClearCreateTime() {
	m.create_time = nil
	m.clearedFields[ticketcomment.FieldCreateTime] = struct{}{}
}

// CreateTimeCleared returns if the "create_time" field was cleared in this mutation.
func (m *TicketCommentMutation) CreateTimeCleared() bool {
	_, ok := m.clearedFields[ticketcomment.FieldCreateTime]
	return ok
}

// ResetCreateTime resets all changes to the "create_time" field.
func (m *TicketCommentMutation) ResetCreateTime() {
	m.create_time = nil
	delete(m.clearedFields, ticketcomment.FieldCreateTime)
}

// SetUpdateTime sets the "update_time" field.
func (m *TicketCommentMutation) SetUpdateTime(t time.Time) {
	m.update_time = &t
}

// UpdateTime returns the value of the "update_time" field in the mutation.
func (m *TicketCommentMutation) UpdateTime() (r time.Time, exists bool) {
	v := m.update_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateTime returns the old "update_time" field's value of the TicketComment entity.
// If the TicketComment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketCommentMutation) OldUpdateTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateTime: %w", err)
	}
	return oldValue.UpdateTime, nil
}

// ClearUpdateTime clears the value of the "update_time" field.
func (m *TicketCommentMutation) ClearUpdateTime() {
	m.update_time = nil
	m.clearedFields[ticketcomment.FieldUpdateTime] = struct{}{}
}

// UpdateTimeCleared returns if the "update_time" field was cleared in this mutation.
func (m *TicketCommentMutation) UpdateTimeCleared() bool {
	_, ok := m.clearedFields[ticketcomment.FieldUpdateTime]
	return ok
}

// ResetUpdateTime resets all changes to the "update_time" field.
func (m *TicketCommentMutation) ResetUpdateTime() {
	m.update_time = nil
	delete(m.clearedFields, ticketcomment.FieldUpdateTime)
}

// SetDeleteTime sets the "delete_time" field.
func (m *TicketCommentMutation) SetDeleteTime(t time.Time) {
	m.delete_time = &t
}

// DeleteTime returns the value of the "delete_time" field in the mutation.
func (m *TicketCommentMutation) DeleteTime() (r time.Time, exists bool) {
	v := m.delete_time
	if v == nil {
		return
	}
	return *v, true
}

// OldDeleteTime returns the old "delete_time" field's value of the TicketComment entity.
// If the TicketComment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketCommentMutation) OldDeleteTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeleteTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeleteTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeleteTime: %w", err)
	}
	return oldValue.DeleteTime, nil
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (m *TicketCommentMutation) ClearDeleteTime() {
	m.delete_time = nil
	m.clearedFields[ticketcomment.FieldDeleteTime] = struct{}{}
}

// DeleteTimeCleared returns if the "delete_time" field was cleared in this mutation.
func (m *TicketCommentMutation) DeleteTimeCleared() bool {
	_, ok := m.clearedFields[ticketcomment.FieldDeleteTime]
	return ok
}

// ResetDeleteTime resets all changes to the "delete_time" field.
func (m *TicketCommentMutation) ResetDeleteTime() {
	m.delete_time = nil
	delete(m.clearedFields, ticketcomment.FieldDeleteTime)
}

// SetTenantID sets the "tenant_id" field.
func (m *TicketCommentMutation) SetTenantID(u uint32) {
	m.tenant_id = &u
	m.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *TicketCommentMutation) TenantID() (r uint32, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the TicketComment entity.
// If the TicketComment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketCommentMutation) OldTenantID(ctx context.Context) (v *uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds u to the "tenant_id" field.
func (m *TicketCommentMutation) AddTenantID(u int32) {
	if m.addtenant_id != nil {
		*m.addtenant_id += u
	} else {
		m.addtenant_id = &u
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (m *TicketCommentMutation) AddedTenantID() (r int32, exists bool) {
	v := m.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearTenantID clears the value of the "tenant_id" field.
func (m *TicketCommentMutation) ClearTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
	m.clearedFields[ticketcomment.FieldTenantID] = struct{}{}
}

// TenantIDCleared returns if the "tenant_id" field was cleared in this mutation.
func (m *TicketCommentMutation) TenantIDCleared() bool {
	_, ok := m.clearedFields[ticketcomment.FieldTenantID]
	return ok
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *TicketCommentMutation) ResetTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
	delete(m.clearedFields, ticketcomment.FieldTenantID)
}

// SetTicketID sets the "ticket_id" field.
func (m *TicketCommentMutation) SetTicketID(s string) {
	m.ticket = &s
}

// TicketID returns the value of the "ticket_id" field in the mutation.
func (m *TicketCommentMutation) TicketID() (r string, exists bool) {
	v := m.ticket
	if v == nil {
		return
	}
	return *v, true
}

// OldTicketID returns the old "ticket_id" field's value of the TicketComment entity.
// If the TicketComment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketCommentMutation) OldTicketID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTicketID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTicketID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTicketID: %w", err)
	}
	return oldValue.TicketID, nil
}

// ResetTicketID resets all changes to the "ticket_id" field.
func (m *TicketCommentMutation) ResetTicketID() {
	m.ticket = nil
}

// SetBody sets the "body" field.
func (m *TicketCommentMutation) SetBody(s string) {
	m.body = &s
}

// Body returns the value of the "body" field in the mutation.
func (m *TicketCommentMutation) Body() (r string, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the TicketComment entity.
// If the TicketComment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketCommentMutation) OldBody(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ResetBody resets all changes to the "body" field.
func (m *TicketCommentMutation) ResetBody() {
	m.body = nil
}

// SetInternal sets the "internal" field.
func (m *TicketCommentMutation) SetInternal(b bool) {
	m.internal = &b
}

// Internal returns the value of the "internal" field in the mutation.
func (m *TicketCommentMutation) Internal() (r bool, exists bool) {
	v := m.internal
	if v == nil {
		return
	}
	return *v, true
}

// OldInternal returns the old "internal" field's value of the TicketComment entity.
// If the TicketComment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketCommentMutation) OldInternal(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldInternal is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldInternal requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldInternal: %w", err)
	}
	return oldValue.Internal, nil
}

// ResetInternal resets all changes to the "internal" field.
func (m *TicketCommentMutation) ResetInternal() {
	m.internal = nil
}

// SetAuthorID sets the "author_id" field.
func (m *TicketCommentMutation) SetAuthorID(u uint32) {
	m.author_id = &u
	m.addauthor_id = nil
}

// AuthorID returns the value of the "author_id" field in the mutation.
func (m *TicketCommentMutation) AuthorID() (r uint32, exists bool) {
	v := m.author_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAuthorID returns the old "author_id" field's value of the TicketComment entity.
// If the TicketComment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketCommentMutation) OldAuthorID(ctx context.Context) (v uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAuthorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAuthorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAuthorID: %w", err)
	}
	return oldValue.AuthorID, nil
}

// AddAuthorID adds u to the "author_id" field.
func (m *TicketCommentMutation) AddAuthorID(u int32) {
	if m.addauthor_id != nil {
		*m.addauthor_id += u
	} else {
		m.addauthor_id = &u
	}
}

// AddedAuthorID returns the value that was added to the "author_id" field in this mutation.
func (m *TicketCommentMutation) AddedAuthorID() (r int32, exists bool) {
	v := m.addauthor_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetAuthorID resets all changes to the "author_id" field.
func (m *TicketCommentMutation) ResetAuthorID() {
	m.author_id = nil
	m.addauthor_id = nil
}

// SetAuthorEmail sets the "author_email" field.
func (m *TicketCommentMutation) SetAuthorEmail(s string) {
	m.author_email = &s
}

// AuthorEmail returns the value of the "author_email" field in the mutation.
func (m *TicketCommentMutation) AuthorEmail() (r string, exists bool) {
	v := m.author_email
	if v == nil {
		return
	}
	return *v, true
}

// OldAuthorEmail returns the old "author_email" field's value of the TicketComment entity.
// If the TicketComment object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TicketCommentMutation) OldAuthorEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAuthorEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAuthorEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAuthorEmail: %w", err)
	}
	return oldValue.AuthorEmail, nil
}

// ClearAuthorEmail clears the value of the "author_email" field.
func (m *TicketCommentMutation) ClearAuthorEmail() {
	m.author_email = nil
	m.clearedFields[ticketcomment.FieldAuthorEmail] = struct{}{}
}

// AuthorEmailCleared returns if the "author_email" field was cleared in this mutation.
func (m *TicketCommentMutation) AuthorEmailCleared() bool {
	_, ok := m.clearedFields[ticketcomment.FieldAuthorEmail]
	return ok
}

// ResetAuthorEmail resets all changes to the "author_email" field.
func (m *TicketCommentMutation) ResetAuthorEmail() {
	m.author_email = nil
	delete(m.clearedFields, ticketcomment.FieldAuthorEmail)
}

// ClearTicket clears the "ticket" edge to the Ticket entity.
func (m *TicketCommentMutation) ClearTicket() {
	m.clearedticket = true
	m.clearedFields[ticketcomment.FieldTicketID] = struct{}{}
}

// TicketCleared reports if the "ticket" edge to the Ticket entity was cleared.
func (m *TicketCommentMutation) TicketCleared() bool {
	return m.clearedticket
}

// TicketIDs returns the "ticket" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TicketID instead. It exists only for internal usage by the builders.
func (m *TicketCommentMutation) TicketIDs() (ids []string) {
	if id := m.ticket; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTicket resets all changes to the "ticket" edge.
func (m *TicketCommentMutation) ResetTicket() {
	m.ticket = nil
	m.clearedticket = false
}

// Where appends a list predicates to the TicketCommentMutation builder.
func (m *TicketCommentMutation) Where(ps ...predicate.TicketComment) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TicketCommentMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TicketCommentMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TicketComment, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TicketCommentMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TicketCommentMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TicketComment).
func (m *TicketCommentMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TicketCommentMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.create_time != nil {
		fields = append(fields, ticketcomment.FieldCreateTime)
	}
	if m.update_time != nil {
		fields = append(fields, ticketcomment.FieldUpdateTime)
	}
	if m.delete_time != nil {
		fields = append(fields, ticketcomment.FieldDeleteTime)
	}
	if m.tenant_id != nil {
		fields = append(fields, ticketcomment.FieldTenantID)
	}
	if m.ticket != nil {
		fields = append(fields, ticketcomment.FieldTicketID)
	}
	if m.body != nil {
		fields = append(fields, ticketcomment.FieldBody)
	}
	if m.internal != nil {
		fields = append(fields, ticketcomment.FieldInternal)
	}
	if m.author_id != nil {
		fields = append(fields, ticketcomment.FieldAuthorID)
	}
	if m.author_email != nil {
		fields = append(fields, ticketcomment.FieldAuthorEmail)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TicketCommentMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case ticketcomment.FieldCreateTime:
		return m.CreateTime()
	case ticketcomment.FieldUpdateTime:
		return m.UpdateTime()
	case ticketcomment.FieldDeleteTime:
		return m.DeleteTime()
	case ticketcomment.FieldTenantID:
		return m.TenantID()
	case ticketcomment.FieldTicketID:
		return m.TicketID()
	case ticketcomment.FieldBody:
		return m.Body()
	case ticketcomment.FieldInternal:
		return m.Internal()
	case ticketcomment.FieldAuthorID:
		return m.AuthorID()
	case ticketcomment.FieldAuthorEmail:
		return m.AuthorEmail()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TicketCommentMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case ticketcomment.FieldCreateTime:
		return m.OldCreateTime(ctx)
	case ticketcomment.FieldUpdateTime:
		return m.OldUpdateTime(ctx)
	case ticketcomment.FieldDeleteTime:
		return m.OldDeleteTime(ctx)
	case ticketcomment.FieldTenantID:
		return m.OldTenantID(ctx)
	case ticketcomment.FieldTicketID:
		return m.OldTicketID(ctx)
	case ticketcomment.FieldBody:
		return m.OldBody(ctx)
	case ticketcomment.FieldInternal:
		return m.OldInternal(ctx)
	case ticketcomment.FieldAuthorID:
		return m.OldAuthorID(ctx)
	case ticketcomment.FieldAuthorEmail:
		return m.OldAuthorEmail(ctx)
	}
	return nil, fmt.Errorf("unknown TicketComment field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TicketCommentMutation) SetField(name string, value ent.Value) error {
	switch name {
	case ticketcomment.FieldCreateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateTime(v)
		return nil
	case ticketcomment.FieldUpdateTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateTime(v)
		return nil
	case ticketcomment.FieldDeleteTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeleteTime(v)
		return nil
	case ticketcomment.FieldTenantID:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case ticketcomment.FieldTicketID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTicketID(v)
		return nil
	case ticketcomment.FieldBody:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case ticketcomment.FieldInternal:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetInternal(v)
		return nil
	case ticketcomment.FieldAuthorID:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuthorID(v)
		return nil
	case ticketcomment.FieldAuthorEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuthorEmail(v)
		return nil
	}
	return fmt.Errorf("unknown TicketComment field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TicketCommentMutation) AddedFields() []string {
	var fields []string
	if m.addtenant_id != nil {
		fields = append(fields, ticketcomment.FieldTenantID)
	}
	if m.addauthor_id != nil {
		fields = append(fields, ticketcomment.FieldAuthorID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TicketCommentMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case ticketcomment.FieldTenantID:
		return m.AddedTenantID()
	case ticketcomment.FieldAuthorID:
		return m.AddedAuthorID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TicketCommentMutation) AddField(name string, value ent.Value) error {
	switch name {
	case ticketcomment.FieldTenantID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTenantID(v)
		return nil
	case ticketcomment.FieldAuthorID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAuthorID(v)
		return nil
	}
	return fmt.Errorf("unknown TicketComment numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TicketCommentMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(ticketcomment.FieldCreateTime) {
		fields = append(fields, ticketcomment.FieldCreateTime)
	}
	if m.FieldCleared(ticketcomment.FieldUpdateTime) {
		fields = append(fields, ticketcomment.FieldUpdateTime)
	}
	if m.FieldCleared(ticketcomment.FieldDeleteTime) {
		fields = append(fields, ticketcomment.FieldDeleteTime)
	}
	if m.FieldCleared(ticketcomment.FieldTenantID) {
		fields = append(fields, ticketcomment.FieldTenantID)
	}
	if m.FieldCleared(ticketcomment.FieldAuthorEmail) {
		fields = append(fields, ticketcomment.FieldAuthorEmail)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TicketCommentMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TicketCommentMutation) ClearField(name string) error {
	switch name {
	case ticketcomment.FieldCreateTime:
		m.ClearCreateTime()
		return nil
	case ticketcomment.FieldUpdateTime:
		m.ClearUpdateTime()
		return nil
	case ticketcomment.FieldDeleteTime:
		m.ClearDeleteTime()
		return nil
	case ticketcomment.FieldTenantID:
		m.ClearTenantID()
		return nil
	case ticketcomment.FieldAuthorEmail:
		m.ClearAuthorEmail()
		return nil
	}
	return fmt.Errorf("unknown TicketComment nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TicketCommentMutation) ResetField(name string) error {
	switch name {
	case ticketcomment.FieldCreateTime:
		m.ResetCreateTime()
		return nil
	case ticketcomment.FieldUpdateTime:
		m.ResetUpdateTime()
		return nil
	case ticketcomment.FieldDeleteTime:
		m.ResetDeleteTime()
		return nil
	case ticketcomment.FieldTenantID:
		m.ResetTenantID()
		return nil
	case ticketcomment.FieldTicketID:
		m.ResetTicketID()
		return nil
	case ticketcomment.FieldBody:
		m.ResetBody()
		return nil
	case ticketcomment.FieldInternal:
		m.ResetInternal()
		return nil
	case ticketcomment.FieldAuthorID:
		m.ResetAuthorID()
		return nil
	case ticketcomment.FieldAuthorEmail:
		m.ResetAuthorEmail()
		return nil
	}
	return fmt.Errorf("unknown TicketComment field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TicketCommentMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.ticket != nil {
		edges = append(edges, ticketcomment.EdgeTicket)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TicketCommentMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case ticketcomment.EdgeTicket:
		if id := m.ticket; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TicketCommentMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TicketCommentMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TicketCommentMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedticket {
		edges = append(edges, ticketcomment.EdgeTicket)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TicketCommentMutation) EdgeCleared(name string) bool {
	switch name {
	case ticketcomment.EdgeTicket:
		return m.clearedticket
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TicketCommentMutation) ClearEdge(name string) error {
	switch name {
	case ticketcomment.EdgeTicket:
		m.ClearTicket()
		return nil
	}
	return fmt.Errorf("unknown TicketComment unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TicketCommentMutation) ResetEdge(name string) error {
	switch name {
	case ticketcomment.EdgeTicket:
		m.ResetTicket()
		return nil
	}
	return fmt.Errorf("unknown TicketComment edge %s", name)
}
