// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticketrule"
)

// TicketRuleCreate is the builder for creating a TicketRule entity.
type TicketRuleCreate struct {
	config
	mutation *TicketRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *TicketRuleCreate) SetCreateTime(v time.Time) *TicketRuleCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableCreateTime(v *time.Time) *TicketRuleCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *TicketRuleCreate) SetUpdateTime(v time.Time) *TicketRuleCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableUpdateTime(v *time.Time) *TicketRuleCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *TicketRuleCreate) SetDeleteTime(v time.Time) *TicketRuleCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableDeleteTime(v *time.Time) *TicketRuleCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TicketRuleCreate) SetTenantID(v uint32) *TicketRuleCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableTenantID(v *uint32) *TicketRuleCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TicketRuleCreate) SetName(v string) *TicketRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *TicketRuleCreate) SetEnabled(v bool) *TicketRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableEnabled(v *bool) *TicketRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *TicketRuleCreate) SetSortOrder(v int) *TicketRuleCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableSortOrder(v *int) *TicketRuleCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetMatch sets the "match" field.
func (_c *TicketRuleCreate) SetMatch(v string) *TicketRuleCreate {
	_c.mutation.SetMatch(v)
	return _c
}

// SetNillableMatch sets the "match" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableMatch(v *string) *TicketRuleCreate {
	if v != nil {
		_c.SetMatch(*v)
	}
	return _c
}

// SetConditions sets the "conditions" field.
func (_c *TicketRuleCreate) SetConditions(v string) *TicketRuleCreate {
	_c.mutation.SetConditions(v)
	return _c
}

// SetNillableConditions sets the "conditions" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableConditions(v *string) *TicketRuleCreate {
	if v != nil {
		_c.SetConditions(*v)
	}
	return _c
}

// SetExpression sets the "expression" field.
func (_c *TicketRuleCreate) SetExpression(v string) *TicketRuleCreate {
	_c.mutation.SetExpression(v)
	return _c
}

// SetNillableExpression sets the "expression" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableExpression(v *string) *TicketRuleCreate {
	if v != nil {
		_c.SetExpression(*v)
	}
	return _c
}

// SetTagKind sets the "tag_kind" field.
func (_c *TicketRuleCreate) SetTagKind(v string) *TicketRuleCreate {
	_c.mutation.SetTagKind(v)
	return _c
}

// SetNillableTagKind sets the "tag_kind" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableTagKind(v *string) *TicketRuleCreate {
	if v != nil {
		_c.SetTagKind(*v)
	}
	return _c
}

// SetTagNames sets the "tag_names" field.
func (_c *TicketRuleCreate) SetTagNames(v string) *TicketRuleCreate {
	_c.mutation.SetTagNames(v)
	return _c
}

// SetNillableTagNames sets the "tag_names" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableTagNames(v *string) *TicketRuleCreate {
	if v != nil {
		_c.SetTagNames(*v)
	}
	return _c
}

// SetActions sets the "actions" field.
func (_c *TicketRuleCreate) SetActions(v string) *TicketRuleCreate {
	_c.mutation.SetActions(v)
	return _c
}

// SetNillableActions sets the "actions" field if the given value is not nil.
func (_c *TicketRuleCreate) SetNillableActions(v *string) *TicketRuleCreate {
	if v != nil {
		_c.SetActions(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TicketRuleCreate) SetID(v string) *TicketRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TicketRuleMutation object of the builder.
func (_c *TicketRuleCreate) Mutation() *TicketRuleMutation {
	return _c.mutation
}

// Save creates the TicketRule in the database.
func (_c *TicketRuleCreate) Save(ctx context.Context) (*TicketRule, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketRuleCreate) SaveX(ctx context.Context) *TicketRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketRuleCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := ticketrule.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := ticketrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := ticketrule.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Match(); !ok {
		v := ticketrule.DefaultMatch
		_c.mutation.SetMatch(v)
	}
	if _, ok := _c.mutation.TagKind(); !ok {
		v := ticketrule.DefaultTagKind
		_c.mutation.SetTagKind(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketRuleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TicketRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ticketrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TicketRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "TicketRule.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "TicketRule.sort_order"`)}
	}
	if _, ok := _c.mutation.Match(); !ok {
		return &ValidationError{Name: "match", err: errors.New(`ent: missing required field "TicketRule.match"`)}
	}
	if _, ok := _c.mutation.TagKind(); !ok {
		return &ValidationError{Name: "tag_kind", err: errors.New(`ent: missing required field "TicketRule.tag_kind"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := ticketrule.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TicketRule.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TicketRuleCreate) sqlSave(ctx context.Context) (*TicketRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TicketRule.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketRuleCreate) createSpec() (*TicketRule, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticketrule.Table, sqlgraph.NewFieldSpec(ticketrule.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(ticketrule.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(ticketrule.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(ticketrule.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(ticketrule.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ticketrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(ticketrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(ticketrule.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Match(); ok {
		_spec.SetField(ticketrule.FieldMatch, field.TypeString, value)
		_node.Match = value
	}
	if value, ok := _c.mutation.Conditions(); ok {
		_spec.SetField(ticketrule.FieldConditions, field.TypeString, value)
		_node.Conditions = value
	}
	if value, ok := _c.mutation.Expression(); ok {
		_spec.SetField(ticketrule.FieldExpression, field.TypeString, value)
		_node.Expression = value
	}
	if value, ok := _c.mutation.TagKind(); ok {
		_spec.SetField(ticketrule.FieldTagKind, field.TypeString, value)
		_node.TagKind = value
	}
	if value, ok := _c.mutation.TagNames(); ok {
		_spec.SetField(ticketrule.FieldTagNames, field.TypeString, value)
		_node.TagNames = value
	}
	if value, ok := _c.mutation.Actions(); ok {
		_spec.SetField(ticketrule.FieldActions, field.TypeString, value)
		_node.Actions = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketRule.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketRuleUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketRuleCreate) OnConflict(opts ...sql.ConflictOption) *TicketRuleUpsertOne {
	_c.conflict = opts
	return &TicketRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketRuleCreate) OnConflictColumns(columns ...string) *TicketRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketRuleUpsertOne{
		create: _c,
	}
}

type (
	// TicketRuleUpsertOne is the builder for "upsert"-ing
	//  one TicketRule node.
	TicketRuleUpsertOne struct {
		create *TicketRuleCreate
	}

	// TicketRuleUpsert is the "OnConflict" setter.
	TicketRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *TicketRuleUpsert) SetUpdateTime(v time.Time) *TicketRuleUpsert {
	u.Set(ticketrule.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateUpdateTime() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *TicketRuleUpsert) ClearUpdateTime() *TicketRuleUpsert {
	u.SetNull(ticketrule.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *TicketRuleUpsert) SetDeleteTime(v time.Time) *TicketRuleUpsert {
	u.Set(ticketrule.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateDeleteTime() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *TicketRuleUpsert) ClearDeleteTime() *TicketRuleUpsert {
	u.SetNull(ticketrule.FieldDeleteTime)
	return u
}

// SetName sets the "name" field.
func (u *TicketRuleUpsert) SetName(v string) *TicketRuleUpsert {
	u.Set(ticketrule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateName() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldName)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *TicketRuleUpsert) SetEnabled(v bool) *TicketRuleUpsert {
	u.Set(ticketrule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateEnabled() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *TicketRuleUpsert) SetSortOrder(v int) *TicketRuleUpsert {
	u.Set(ticketrule.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateSortOrder() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *TicketRuleUpsert) AddSortOrder(v int) *TicketRuleUpsert {
	u.Add(ticketrule.FieldSortOrder, v)
	return u
}

// SetMatch sets the "match" field.
func (u *TicketRuleUpsert) SetMatch(v string) *TicketRuleUpsert {
	u.Set(ticketrule.FieldMatch, v)
	return u
}

// UpdateMatch sets the "match" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateMatch() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldMatch)
	return u
}

// SetConditions sets the "conditions" field.
func (u *TicketRuleUpsert) SetConditions(v string) *TicketRuleUpsert {
	u.Set(ticketrule.FieldConditions, v)
	return u
}

// UpdateConditions sets the "conditions" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateConditions() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldConditions)
	return u
}

// ClearConditions clears the value of the "conditions" field.
func (u *TicketRuleUpsert) ClearConditions() *TicketRuleUpsert {
	u.SetNull(ticketrule.FieldConditions)
	return u
}

// SetExpression sets the "expression" field.
func (u *TicketRuleUpsert) SetExpression(v string) *TicketRuleUpsert {
	u.Set(ticketrule.FieldExpression, v)
	return u
}

// UpdateExpression sets the "expression" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateExpression() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldExpression)
	return u
}

// ClearExpression clears the value of the "expression" field.
func (u *TicketRuleUpsert) ClearExpression() *TicketRuleUpsert {
	u.SetNull(ticketrule.FieldExpression)
	return u
}

// SetTagKind sets the "tag_kind" field.
func (u *TicketRuleUpsert) SetTagKind(v string) *TicketRuleUpsert {
	u.Set(ticketrule.FieldTagKind, v)
	return u
}

// UpdateTagKind sets the "tag_kind" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateTagKind() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldTagKind)
	return u
}

// SetTagNames sets the "tag_names" field.
func (u *TicketRuleUpsert) SetTagNames(v string) *TicketRuleUpsert {
	u.Set(ticketrule.FieldTagNames, v)
	return u
}

// UpdateTagNames sets the "tag_names" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateTagNames() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldTagNames)
	return u
}

// ClearTagNames clears the value of the "tag_names" field.
func (u *TicketRuleUpsert) ClearTagNames() *TicketRuleUpsert {
	u.SetNull(ticketrule.FieldTagNames)
	return u
}

// SetActions sets the "actions" field.
func (u *TicketRuleUpsert) SetActions(v string) *TicketRuleUpsert {
	u.Set(ticketrule.FieldActions, v)
	return u
}

// UpdateActions sets the "actions" field to the value that was provided on create.
func (u *TicketRuleUpsert) UpdateActions() *TicketRuleUpsert {
	u.SetExcluded(ticketrule.FieldActions)
	return u
}

// ClearActions clears the value of the "actions" field.
func (u *TicketRuleUpsert) ClearActions() *TicketRuleUpsert {
	u.SetNull(ticketrule.FieldActions)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TicketRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ticketrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketRuleUpsertOne) UpdateNewValues() *TicketRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ticketrule.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(ticketrule.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(ticketrule.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketRuleUpsertOne) Ignore() *TicketRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketRuleUpsertOne) DoNothing() *TicketRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketRuleCreate.OnConflict
// documentation for more info.
func (u *TicketRuleUpsertOne) Update(set func(*TicketRuleUpsert)) *TicketRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TicketRuleUpsertOne) SetUpdateTime(v time.Time) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateUpdateTime() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *TicketRuleUpsertOne) ClearUpdateTime() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *TicketRuleUpsertOne) SetDeleteTime(v time.Time) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateDeleteTime() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *TicketRuleUpsertOne) ClearDeleteTime() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *TicketRuleUpsertOne) SetName(v string) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateName() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *TicketRuleUpsertOne) SetEnabled(v bool) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateEnabled() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *TicketRuleUpsertOne) SetSortOrder(v int) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *TicketRuleUpsertOne) AddSortOrder(v int) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateSortOrder() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateSortOrder()
	})
}

// SetMatch sets the "match" field.
func (u *TicketRuleUpsertOne) SetMatch(v string) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetMatch(v)
	})
}

// UpdateMatch sets the "match" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateMatch() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateMatch()
	})
}

// SetConditions sets the "conditions" field.
func (u *TicketRuleUpsertOne) SetConditions(v string) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetConditions(v)
	})
}

// UpdateConditions sets the "conditions" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateConditions() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateConditions()
	})
}

// ClearConditions clears the value of the "conditions" field.
func (u *TicketRuleUpsertOne) ClearConditions() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearConditions()
	})
}

// SetExpression sets the "expression" field.
func (u *TicketRuleUpsertOne) SetExpression(v string) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetExpression(v)
	})
}

// UpdateExpression sets the "expression" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateExpression() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateExpression()
	})
}

// ClearExpression clears the value of the "expression" field.
func (u *TicketRuleUpsertOne) ClearExpression() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearExpression()
	})
}

// SetTagKind sets the "tag_kind" field.
func (u *TicketRuleUpsertOne) SetTagKind(v string) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetTagKind(v)
	})
}

// UpdateTagKind sets the "tag_kind" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateTagKind() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateTagKind()
	})
}

// SetTagNames sets the "tag_names" field.
func (u *TicketRuleUpsertOne) SetTagNames(v string) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetTagNames(v)
	})
}

// UpdateTagNames sets the "tag_names" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateTagNames() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateTagNames()
	})
}

// ClearTagNames clears the value of the "tag_names" field.
func (u *TicketRuleUpsertOne) ClearTagNames() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearTagNames()
	})
}

// SetActions sets the "actions" field.
func (u *TicketRuleUpsertOne) SetActions(v string) *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetActions(v)
	})
}

// UpdateActions sets the "actions" field to the value that was provided on create.
func (u *TicketRuleUpsertOne) UpdateActions() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateActions()
	})
}

// ClearActions clears the value of the "actions" field.
func (u *TicketRuleUpsertOne) ClearActions() *TicketRuleUpsertOne {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearActions()
	})
}

// Exec executes the query.
func (u *TicketRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketRuleUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TicketRuleUpsertOne.ID is not supported by MySQL driver. Use TicketRuleUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketRuleUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketRuleCreateBulk is the builder for creating many TicketRule entities in bulk.
type TicketRuleCreateBulk struct {
	config
	err      error
	builders []*TicketRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the TicketRule entities in the database.
func (_c *TicketRuleCreateBulk) Save(ctx context.Context) ([]*TicketRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketRuleCreateBulk) SaveX(ctx context.Context) []*TicketRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketRuleUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketRuleUpsertBulk {
	_c.conflict = opts
	return &TicketRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketRuleCreateBulk) OnConflictColumns(columns ...string) *TicketRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketRuleUpsertBulk{
		create: _c,
	}
}

// TicketRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of TicketRule nodes.
type TicketRuleUpsertBulk struct {
	create *TicketRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TicketRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ticketrule.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketRuleUpsertBulk) UpdateNewValues() *TicketRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ticketrule.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(ticketrule.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(ticketrule.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketRuleUpsertBulk) Ignore() *TicketRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketRuleUpsertBulk) DoNothing() *TicketRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketRuleCreateBulk.OnConflict
// documentation for more info.
func (u *TicketRuleUpsertBulk) Update(set func(*TicketRuleUpsert)) *TicketRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TicketRuleUpsertBulk) SetUpdateTime(v time.Time) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateUpdateTime() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *TicketRuleUpsertBulk) ClearUpdateTime() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *TicketRuleUpsertBulk) SetDeleteTime(v time.Time) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateDeleteTime() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *TicketRuleUpsertBulk) ClearDeleteTime() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *TicketRuleUpsertBulk) SetName(v string) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateName() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateName()
	})
}

// SetEnabled sets the "enabled" field.
func (u *TicketRuleUpsertBulk) SetEnabled(v bool) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateEnabled() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *TicketRuleUpsertBulk) SetSortOrder(v int) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *TicketRuleUpsertBulk) AddSortOrder(v int) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateSortOrder() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateSortOrder()
	})
}

// SetMatch sets the "match" field.
func (u *TicketRuleUpsertBulk) SetMatch(v string) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetMatch(v)
	})
}

// UpdateMatch sets the "match" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateMatch() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateMatch()
	})
}

// SetConditions sets the "conditions" field.
func (u *TicketRuleUpsertBulk) SetConditions(v string) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetConditions(v)
	})
}

// UpdateConditions sets the "conditions" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateConditions() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateConditions()
	})
}

// ClearConditions clears the value of the "conditions" field.
func (u *TicketRuleUpsertBulk) ClearConditions() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearConditions()
	})
}

// SetExpression sets the "expression" field.
func (u *TicketRuleUpsertBulk) SetExpression(v string) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetExpression(v)
	})
}

// UpdateExpression sets the "expression" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateExpression() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateExpression()
	})
}

// ClearExpression clears the value of the "expression" field.
func (u *TicketRuleUpsertBulk) ClearExpression() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearExpression()
	})
}

// SetTagKind sets the "tag_kind" field.
func (u *TicketRuleUpsertBulk) SetTagKind(v string) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetTagKind(v)
	})
}

// UpdateTagKind sets the "tag_kind" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateTagKind() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateTagKind()
	})
}

// SetTagNames sets the "tag_names" field.
func (u *TicketRuleUpsertBulk) SetTagNames(v string) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetTagNames(v)
	})
}

// UpdateTagNames sets the "tag_names" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateTagNames() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateTagNames()
	})
}

// ClearTagNames clears the value of the "tag_names" field.
func (u *TicketRuleUpsertBulk) ClearTagNames() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearTagNames()
	})
}

// SetActions sets the "actions" field.
func (u *TicketRuleUpsertBulk) SetActions(v string) *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.SetActions(v)
	})
}

// UpdateActions sets the "actions" field to the value that was provided on create.
func (u *TicketRuleUpsertBulk) UpdateActions() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.UpdateActions()
	})
}

// ClearActions clears the value of the "actions" field.
func (u *TicketRuleUpsertBulk) ClearActions() *TicketRuleUpsertBulk {
	return u.Update(func(s *TicketRuleUpsert) {
		s.ClearActions()
	})
}

// Exec executes the query.
func (u *TicketRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
