// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticketrule"
)

// TicketRule is the model entity for the TicketRule schema.
type TicketRule struct {
	config `json:"-"`
	// ID of the ent.
	// UUID primary key
	ID string `json:"id,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Evaluation order (lower first)
	SortOrder int `json:"sort_order,omitempty"`
	// ALL (AND) or ANY (OR)
	Match string `json:"match,omitempty"`
	// JSON: [{field,operator,value}]
	Conditions string `json:"conditions,omitempty"`
	// Optional raw CEL expression (overrides conditions)
	Expression string `json:"expression,omitempty"`
	// Kind of tag created/applied: TAG or CATEGORY
	TagKind string `json:"tag_kind,omitempty"`
	// JSON: tag names to apply when the rule matches
	TagNames     string `json:"tag_names,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TicketRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticketrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case ticketrule.FieldTenantID, ticketrule.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case ticketrule.FieldID, ticketrule.FieldName, ticketrule.FieldMatch, ticketrule.FieldConditions, ticketrule.FieldExpression, ticketrule.FieldTagKind, ticketrule.FieldTagNames:
			values[i] = new(sql.NullString)
		case ticketrule.FieldCreateTime, ticketrule.FieldUpdateTime, ticketrule.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TicketRule fields.
func (_m *TicketRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticketrule.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case ticketrule.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case ticketrule.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case ticketrule.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case ticketrule.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case ticketrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case ticketrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case ticketrule.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case ticketrule.FieldMatch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match", values[i])
			} else if value.Valid {
				_m.Match = value.String
			}
		case ticketrule.FieldConditions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field conditions", values[i])
			} else if value.Valid {
				_m.Conditions = value.String
			}
		case ticketrule.FieldExpression:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field expression", values[i])
			} else if value.Valid {
				_m.Expression = value.String
			}
		case ticketrule.FieldTagKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag_kind", values[i])
			} else if value.Valid {
				_m.TagKind = value.String
			}
		case ticketrule.FieldTagNames:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag_names", values[i])
			} else if value.Valid {
				_m.TagNames = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TicketRule.
// This includes values selected through modifiers, order, etc.
func (_m *TicketRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TicketRule.
// Note that you need to call TicketRule.Unwrap() before calling this method if this TicketRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TicketRule) Update() *TicketRuleUpdateOne {
	return NewTicketRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TicketRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TicketRule) Unwrap() *TicketRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TicketRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TicketRule) String() string {
	var builder strings.Builder
	builder.WriteString("TicketRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("match=")
	builder.WriteString(_m.Match)
	builder.WriteString(", ")
	builder.WriteString("conditions=")
	builder.WriteString(_m.Conditions)
	builder.WriteString(", ")
	builder.WriteString("expression=")
	builder.WriteString(_m.Expression)
	builder.WriteString(", ")
	builder.WriteString("tag_kind=")
	builder.WriteString(_m.TagKind)
	builder.WriteString(", ")
	builder.WriteString("tag_names=")
	builder.WriteString(_m.TagNames)
	builder.WriteByte(')')
	return builder.String()
}

// TicketRules is a parsable slice of TicketRule.
type TicketRules []*TicketRule
