// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticket"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/tickettag"
)

// TicketTagCreate is the builder for creating a TicketTag entity.
type TicketTagCreate struct {
	config
	mutation *TicketTagMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *TicketTagCreate) SetCreateTime(v time.Time) *TicketTagCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *TicketTagCreate) SetNillableCreateTime(v *time.Time) *TicketTagCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *TicketTagCreate) SetUpdateTime(v time.Time) *TicketTagCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *TicketTagCreate) SetNillableUpdateTime(v *time.Time) *TicketTagCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *TicketTagCreate) SetDeleteTime(v time.Time) *TicketTagCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *TicketTagCreate) SetNillableDeleteTime(v *time.Time) *TicketTagCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TicketTagCreate) SetTenantID(v uint32) *TicketTagCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TicketTagCreate) SetNillableTenantID(v *uint32) *TicketTagCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TicketTagCreate) SetName(v string) *TicketTagCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *TicketTagCreate) SetKind(v string) *TicketTagCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *TicketTagCreate) SetNillableKind(v *string) *TicketTagCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetColor sets the "color" field.
func (_c *TicketTagCreate) SetColor(v string) *TicketTagCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_c *TicketTagCreate) SetNillableColor(v *string) *TicketTagCreate {
	if v != nil {
		_c.SetColor(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *TicketTagCreate) SetDescription(v string) *TicketTagCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TicketTagCreate) SetNillableDescription(v *string) *TicketTagCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TicketTagCreate) SetID(v string) *TicketTagCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_c *TicketTagCreate) AddTicketIDs(ids ...string) *TicketTagCreate {
	_c.mutation.AddTicketIDs(ids...)
	return _c
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_c *TicketTagCreate) AddTickets(v ...*Ticket) *TicketTagCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketIDs(ids...)
}

// Mutation returns the TicketTagMutation object of the builder.
func (_c *TicketTagCreate) Mutation() *TicketTagMutation {
	return _c.mutation
}

// Save creates the TicketTag in the database.
func (_c *TicketTagCreate) Save(ctx context.Context) (*TicketTag, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketTagCreate) SaveX(ctx context.Context) *TicketTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketTagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketTagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketTagCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := tickettag.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := tickettag.DefaultKind
		_c.mutation.SetKind(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketTagCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TicketTag.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := tickettag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TicketTag.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "TicketTag.kind"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := tickettag.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TicketTag.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TicketTagCreate) sqlSave(ctx context.Context) (*TicketTag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TicketTag.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketTagCreate) createSpec() (*TicketTag, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketTag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tickettag.Table, sqlgraph.NewFieldSpec(tickettag.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(tickettag.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(tickettag.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(tickettag.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tickettag.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tickettag.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(tickettag.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(tickettag.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(tickettag.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tickettag.TicketsTable,
			Columns: tickettag.TicketsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketTag.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketTagUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketTagCreate) OnConflict(opts ...sql.ConflictOption) *TicketTagUpsertOne {
	_c.conflict = opts
	return &TicketTagUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketTagCreate) OnConflictColumns(columns ...string) *TicketTagUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketTagUpsertOne{
		create: _c,
	}
}

type (
	// TicketTagUpsertOne is the builder for "upsert"-ing
	//  one TicketTag node.
	TicketTagUpsertOne struct {
		create *TicketTagCreate
	}

	// TicketTagUpsert is the "OnConflict" setter.
	TicketTagUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *TicketTagUpsert) SetUpdateTime(v time.Time) *TicketTagUpsert {
	u.Set(tickettag.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TicketTagUpsert) UpdateUpdateTime() *TicketTagUpsert {
	u.SetExcluded(tickettag.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *TicketTagUpsert) ClearUpdateTime() *TicketTagUpsert {
	u.SetNull(tickettag.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *TicketTagUpsert) SetDeleteTime(v time.Time) *TicketTagUpsert {
	u.Set(tickettag.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *TicketTagUpsert) UpdateDeleteTime() *TicketTagUpsert {
	u.SetExcluded(tickettag.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *TicketTagUpsert) ClearDeleteTime() *TicketTagUpsert {
	u.SetNull(tickettag.FieldDeleteTime)
	return u
}

// SetName sets the "name" field.
func (u *TicketTagUpsert) SetName(v string) *TicketTagUpsert {
	u.Set(tickettag.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TicketTagUpsert) UpdateName() *TicketTagUpsert {
	u.SetExcluded(tickettag.FieldName)
	return u
}

// SetKind sets the "kind" field.
func (u *TicketTagUpsert) SetKind(v string) *TicketTagUpsert {
	u.Set(tickettag.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *TicketTagUpsert) UpdateKind() *TicketTagUpsert {
	u.SetExcluded(tickettag.FieldKind)
	return u
}

// SetColor sets the "color" field.
func (u *TicketTagUpsert) SetColor(v string) *TicketTagUpsert {
	u.Set(tickettag.FieldColor, v)
	return u
}

// UpdateColor sets the "color" field to the value that was provided on create.
func (u *TicketTagUpsert) UpdateColor() *TicketTagUpsert {
	u.SetExcluded(tickettag.FieldColor)
	return u
}

// ClearColor clears the value of the "color" field.
func (u *TicketTagUpsert) ClearColor() *TicketTagUpsert {
	u.SetNull(tickettag.FieldColor)
	return u
}

// SetDescription sets the "description" field.
func (u *TicketTagUpsert) SetDescription(v string) *TicketTagUpsert {
	u.Set(tickettag.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TicketTagUpsert) UpdateDescription() *TicketTagUpsert {
	u.SetExcluded(tickettag.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TicketTagUpsert) ClearDescription() *TicketTagUpsert {
	u.SetNull(tickettag.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TicketTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tickettag.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketTagUpsertOne) UpdateNewValues() *TicketTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tickettag.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(tickettag.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(tickettag.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketTag.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketTagUpsertOne) Ignore() *TicketTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketTagUpsertOne) DoNothing() *TicketTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketTagCreate.OnConflict
// documentation for more info.
func (u *TicketTagUpsertOne) Update(set func(*TicketTagUpsert)) *TicketTagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TicketTagUpsertOne) SetUpdateTime(v time.Time) *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TicketTagUpsertOne) UpdateUpdateTime() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *TicketTagUpsertOne) ClearUpdateTime() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *TicketTagUpsertOne) SetDeleteTime(v time.Time) *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *TicketTagUpsertOne) UpdateDeleteTime() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *TicketTagUpsertOne) ClearDeleteTime() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *TicketTagUpsertOne) SetName(v string) *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TicketTagUpsertOne) UpdateName() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *TicketTagUpsertOne) SetKind(v string) *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *TicketTagUpsertOne) UpdateKind() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateKind()
	})
}

// SetColor sets the "color" field.
func (u *TicketTagUpsertOne) SetColor(v string) *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetColor(v)
	})
}

// UpdateColor sets the "color" field to the value that was provided on create.
func (u *TicketTagUpsertOne) UpdateColor() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateColor()
	})
}

// ClearColor clears the value of the "color" field.
func (u *TicketTagUpsertOne) ClearColor() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.ClearColor()
	})
}

// SetDescription sets the "description" field.
func (u *TicketTagUpsertOne) SetDescription(v string) *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TicketTagUpsertOne) UpdateDescription() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TicketTagUpsertOne) ClearDescription() *TicketTagUpsertOne {
	return u.Update(func(s *TicketTagUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *TicketTagUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketTagCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketTagUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketTagUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TicketTagUpsertOne.ID is not supported by MySQL driver. Use TicketTagUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketTagUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketTagCreateBulk is the builder for creating many TicketTag entities in bulk.
type TicketTagCreateBulk struct {
	config
	err      error
	builders []*TicketTagCreate
	conflict []sql.ConflictOption
}

// Save creates the TicketTag entities in the database.
func (_c *TicketTagCreateBulk) Save(ctx context.Context) ([]*TicketTag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketTag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketTagCreateBulk) SaveX(ctx context.Context) []*TicketTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketTagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketTagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketTag.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketTagUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketTagCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketTagUpsertBulk {
	_c.conflict = opts
	return &TicketTagUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketTag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketTagCreateBulk) OnConflictColumns(columns ...string) *TicketTagUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketTagUpsertBulk{
		create: _c,
	}
}

// TicketTagUpsertBulk is the builder for "upsert"-ing
// a bulk of TicketTag nodes.
type TicketTagUpsertBulk struct {
	create *TicketTagCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TicketTag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tickettag.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketTagUpsertBulk) UpdateNewValues() *TicketTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tickettag.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(tickettag.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(tickettag.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketTag.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketTagUpsertBulk) Ignore() *TicketTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketTagUpsertBulk) DoNothing() *TicketTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketTagCreateBulk.OnConflict
// documentation for more info.
func (u *TicketTagUpsertBulk) Update(set func(*TicketTagUpsert)) *TicketTagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketTagUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TicketTagUpsertBulk) SetUpdateTime(v time.Time) *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TicketTagUpsertBulk) UpdateUpdateTime() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *TicketTagUpsertBulk) ClearUpdateTime() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *TicketTagUpsertBulk) SetDeleteTime(v time.Time) *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *TicketTagUpsertBulk) UpdateDeleteTime() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *TicketTagUpsertBulk) ClearDeleteTime() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *TicketTagUpsertBulk) SetName(v string) *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TicketTagUpsertBulk) UpdateName() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *TicketTagUpsertBulk) SetKind(v string) *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *TicketTagUpsertBulk) UpdateKind() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateKind()
	})
}

// SetColor sets the "color" field.
func (u *TicketTagUpsertBulk) SetColor(v string) *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetColor(v)
	})
}

// UpdateColor sets the "color" field to the value that was provided on create.
func (u *TicketTagUpsertBulk) UpdateColor() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateColor()
	})
}

// ClearColor clears the value of the "color" field.
func (u *TicketTagUpsertBulk) ClearColor() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.ClearColor()
	})
}

// SetDescription sets the "description" field.
func (u *TicketTagUpsertBulk) SetDescription(v string) *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TicketTagUpsertBulk) UpdateDescription() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TicketTagUpsertBulk) ClearDescription() *TicketTagUpsertBulk {
	return u.Update(func(s *TicketTagUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *TicketTagUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketTagCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketTagCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketTagUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
