// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticket"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticketcomment"
)

// TicketUpdate is the builder for updating Ticket entities.
type TicketUpdate struct {
	config
	hooks     []Hook
	mutation  *TicketMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TicketUpdate builder.
func (_u *TicketUpdate) Where(ps ...predicate.Ticket) *TicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *TicketUpdate) SetCreateBy(v uint32) *TicketUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableCreateBy(v *uint32) *TicketUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *TicketUpdate) AddCreateBy(v int32) *TicketUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *TicketUpdate) ClearCreateBy() *TicketUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TicketUpdate) SetUpdateTime(v time.Time) *TicketUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableUpdateTime(v *time.Time) *TicketUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *TicketUpdate) ClearUpdateTime() *TicketUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *TicketUpdate) SetDeleteTime(v time.Time) *TicketUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableDeleteTime(v *time.Time) *TicketUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *TicketUpdate) ClearDeleteTime() *TicketUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *TicketUpdate) SetExternalID(v string) *TicketUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableExternalID(v *string) *TicketUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *TicketUpdate) ClearExternalID() *TicketUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *TicketUpdate) SetSubject(v string) *TicketUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableSubject(v *string) *TicketUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TicketUpdate) SetDescription(v string) *TicketUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableDescription(v *string) *TicketUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TicketUpdate) ClearDescription() *TicketUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TicketUpdate) SetStatus(v string) *TicketUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableStatus(v *string) *TicketUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TicketUpdate) SetPriority(v string) *TicketUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TicketUpdate) SetNillablePriority(v *string) *TicketUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *TicketUpdate) SetSource(v string) *TicketUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableSource(v *string) *TicketUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRequesterEmail sets the "requester_email" field.
func (_u *TicketUpdate) SetRequesterEmail(v string) *TicketUpdate {
	_u.mutation.SetRequesterEmail(v)
	return _u
}

// SetNillableRequesterEmail sets the "requester_email" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableRequesterEmail(v *string) *TicketUpdate {
	if v != nil {
		_u.SetRequesterEmail(*v)
	}
	return _u
}

// ClearRequesterEmail clears the value of the "requester_email" field.
func (_u *TicketUpdate) ClearRequesterEmail() *TicketUpdate {
	_u.mutation.ClearRequesterEmail()
	return _u
}

// SetRequesterName sets the "requester_name" field.
func (_u *TicketUpdate) SetRequesterName(v string) *TicketUpdate {
	_u.mutation.SetRequesterName(v)
	return _u
}

// SetNillableRequesterName sets the "requester_name" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableRequesterName(v *string) *TicketUpdate {
	if v != nil {
		_u.SetRequesterName(*v)
	}
	return _u
}

// ClearRequesterName clears the value of the "requester_name" field.
func (_u *TicketUpdate) ClearRequesterName() *TicketUpdate {
	_u.mutation.ClearRequesterName()
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *TicketUpdate) SetRecipient(v string) *TicketUpdate {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableRecipient(v *string) *TicketUpdate {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// ClearRecipient clears the value of the "recipient" field.
func (_u *TicketUpdate) ClearRecipient() *TicketUpdate {
	_u.mutation.ClearRecipient()
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *TicketUpdate) SetAssigneeID(v uint32) *TicketUpdate {
	_u.mutation.ResetAssigneeID()
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableAssigneeID(v *uint32) *TicketUpdate {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// AddAssigneeID adds value to the "assignee_id" field.
func (_u *TicketUpdate) AddAssigneeID(v int32) *TicketUpdate {
	_u.mutation.AddAssigneeID(v)
	return _u
}

// AddCommentIDs adds the "comments" edge to the TicketComment entity by IDs.
func (_u *TicketUpdate) AddCommentIDs(ids ...string) *TicketUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the TicketComment entity.
func (_u *TicketUpdate) AddComments(v ...*TicketComment) *TicketUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_u *TicketUpdate) Mutation() *TicketMutation {
	return _u.mutation
}

// ClearComments clears all "comments" edges to the TicketComment entity.
func (_u *TicketUpdate) ClearComments() *TicketUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to TicketComment entities by IDs.
func (_u *TicketUpdate) RemoveCommentIDs(ids ...string) *TicketUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to TicketComment entities.
func (_u *TicketUpdate) RemoveComments(v ...*TicketComment) *TicketUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketUpdate) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := ticket.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Ticket.subject": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TicketUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TicketUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticket.Table, ticket.Columns, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(ticket.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(ticket.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(ticket.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(ticket.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(ticket.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(ticket.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(ticket.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(ticket.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(ticket.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(ticket.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(ticket.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(ticket.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ticket.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ticket.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(ticket.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(ticket.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequesterEmail(); ok {
		_spec.SetField(ticket.FieldRequesterEmail, field.TypeString, value)
	}
	if _u.mutation.RequesterEmailCleared() {
		_spec.ClearField(ticket.FieldRequesterEmail, field.TypeString)
	}
	if value, ok := _u.mutation.RequesterName(); ok {
		_spec.SetField(ticket.FieldRequesterName, field.TypeString, value)
	}
	if _u.mutation.RequesterNameCleared() {
		_spec.ClearField(ticket.FieldRequesterName, field.TypeString)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(ticket.FieldRecipient, field.TypeString, value)
	}
	if _u.mutation.RecipientCleared() {
		_spec.ClearField(ticket.FieldRecipient, field.TypeString)
	}
	if value, ok := _u.mutation.AssigneeID(); ok {
		_spec.SetField(ticket.FieldAssigneeID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAssigneeID(); ok {
		_spec.AddField(ticket.FieldAssigneeID, field.TypeUint32, value)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.CommentsTable,
			Columns: []string{ticket.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketcomment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.CommentsTable,
			Columns: []string{ticket.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketcomment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.CommentsTable,
			Columns: []string{ticket.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketcomment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketUpdateOne is the builder for updating a single Ticket entity.
type TicketUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TicketMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *TicketUpdateOne) SetCreateBy(v uint32) *TicketUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableCreateBy(v *uint32) *TicketUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *TicketUpdateOne) AddCreateBy(v int32) *TicketUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *TicketUpdateOne) ClearCreateBy() *TicketUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TicketUpdateOne) SetUpdateTime(v time.Time) *TicketUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableUpdateTime(v *time.Time) *TicketUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *TicketUpdateOne) ClearUpdateTime() *TicketUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *TicketUpdateOne) SetDeleteTime(v time.Time) *TicketUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableDeleteTime(v *time.Time) *TicketUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *TicketUpdateOne) ClearDeleteTime() *TicketUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *TicketUpdateOne) SetExternalID(v string) *TicketUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableExternalID(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *TicketUpdateOne) ClearExternalID() *TicketUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *TicketUpdateOne) SetSubject(v string) *TicketUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableSubject(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TicketUpdateOne) SetDescription(v string) *TicketUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableDescription(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TicketUpdateOne) ClearDescription() *TicketUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TicketUpdateOne) SetStatus(v string) *TicketUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableStatus(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TicketUpdateOne) SetPriority(v string) *TicketUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillablePriority(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *TicketUpdateOne) SetSource(v string) *TicketUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableSource(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRequesterEmail sets the "requester_email" field.
func (_u *TicketUpdateOne) SetRequesterEmail(v string) *TicketUpdateOne {
	_u.mutation.SetRequesterEmail(v)
	return _u
}

// SetNillableRequesterEmail sets the "requester_email" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableRequesterEmail(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetRequesterEmail(*v)
	}
	return _u
}

// ClearRequesterEmail clears the value of the "requester_email" field.
func (_u *TicketUpdateOne) ClearRequesterEmail() *TicketUpdateOne {
	_u.mutation.ClearRequesterEmail()
	return _u
}

// SetRequesterName sets the "requester_name" field.
func (_u *TicketUpdateOne) SetRequesterName(v string) *TicketUpdateOne {
	_u.mutation.SetRequesterName(v)
	return _u
}

// SetNillableRequesterName sets the "requester_name" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableRequesterName(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetRequesterName(*v)
	}
	return _u
}

// ClearRequesterName clears the value of the "requester_name" field.
func (_u *TicketUpdateOne) ClearRequesterName() *TicketUpdateOne {
	_u.mutation.ClearRequesterName()
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *TicketUpdateOne) SetRecipient(v string) *TicketUpdateOne {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableRecipient(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// ClearRecipient clears the value of the "recipient" field.
func (_u *TicketUpdateOne) ClearRecipient() *TicketUpdateOne {
	_u.mutation.ClearRecipient()
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *TicketUpdateOne) SetAssigneeID(v uint32) *TicketUpdateOne {
	_u.mutation.ResetAssigneeID()
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableAssigneeID(v *uint32) *TicketUpdateOne {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// AddAssigneeID adds value to the "assignee_id" field.
func (_u *TicketUpdateOne) AddAssigneeID(v int32) *TicketUpdateOne {
	_u.mutation.AddAssigneeID(v)
	return _u
}

// AddCommentIDs adds the "comments" edge to the TicketComment entity by IDs.
func (_u *TicketUpdateOne) AddCommentIDs(ids ...string) *TicketUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the TicketComment entity.
func (_u *TicketUpdateOne) AddComments(v ...*TicketComment) *TicketUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_u *TicketUpdateOne) Mutation() *TicketMutation {
	return _u.mutation
}

// ClearComments clears all "comments" edges to the TicketComment entity.
func (_u *TicketUpdateOne) ClearComments() *TicketUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to TicketComment entities by IDs.
func (_u *TicketUpdateOne) RemoveCommentIDs(ids ...string) *TicketUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to TicketComment entities.
func (_u *TicketUpdateOne) RemoveComments(v ...*TicketComment) *TicketUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// Where appends a list predicates to the TicketUpdate builder.
func (_u *TicketUpdateOne) Where(ps ...predicate.Ticket) *TicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketUpdateOne) Select(field string, fields ...string) *TicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ticket entity.
func (_u *TicketUpdateOne) Save(ctx context.Context) (*Ticket, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketUpdateOne) SaveX(ctx context.Context) *Ticket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketUpdateOne) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := ticket.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Ticket.subject": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TicketUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TicketUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TicketUpdateOne) sqlSave(ctx context.Context) (_node *Ticket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticket.Table, ticket.Columns, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ticket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticket.FieldID)
		for _, f := range fields {
			if !ticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(ticket.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(ticket.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(ticket.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(ticket.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(ticket.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(ticket.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(ticket.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(ticket.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(ticket.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(ticket.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(ticket.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(ticket.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(ticket.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(ticket.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(ticket.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(ticket.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequesterEmail(); ok {
		_spec.SetField(ticket.FieldRequesterEmail, field.TypeString, value)
	}
	if _u.mutation.RequesterEmailCleared() {
		_spec.ClearField(ticket.FieldRequesterEmail, field.TypeString)
	}
	if value, ok := _u.mutation.RequesterName(); ok {
		_spec.SetField(ticket.FieldRequesterName, field.TypeString, value)
	}
	if _u.mutation.RequesterNameCleared() {
		_spec.ClearField(ticket.FieldRequesterName, field.TypeString)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(ticket.FieldRecipient, field.TypeString, value)
	}
	if _u.mutation.RecipientCleared() {
		_spec.ClearField(ticket.FieldRecipient, field.TypeString)
	}
	if value, ok := _u.mutation.AssigneeID(); ok {
		_spec.SetField(ticket.FieldAssigneeID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAssigneeID(); ok {
		_spec.AddField(ticket.FieldAssigneeID, field.TypeUint32, value)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.CommentsTable,
			Columns: []string{ticket.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketcomment.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.CommentsTable,
			Columns: []string{ticket.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketcomment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.CommentsTable,
			Columns: []string{ticket.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketcomment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Ticket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
