// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticketattachment"
)

// TicketAttachmentCreate is the builder for creating a TicketAttachment entity.
type TicketAttachmentCreate struct {
	config
	mutation *TicketAttachmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *TicketAttachmentCreate) SetCreateTime(v time.Time) *TicketAttachmentCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableCreateTime(v *time.Time) *TicketAttachmentCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *TicketAttachmentCreate) SetUpdateTime(v time.Time) *TicketAttachmentCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableUpdateTime(v *time.Time) *TicketAttachmentCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *TicketAttachmentCreate) SetDeleteTime(v time.Time) *TicketAttachmentCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableDeleteTime(v *time.Time) *TicketAttachmentCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TicketAttachmentCreate) SetTenantID(v uint32) *TicketAttachmentCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableTenantID(v *uint32) *TicketAttachmentCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetTicketID sets the "ticket_id" field.
func (_c *TicketAttachmentCreate) SetTicketID(v string) *TicketAttachmentCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetFilename sets the "filename" field.
func (_c *TicketAttachmentCreate) SetFilename(v string) *TicketAttachmentCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableFilename(v *string) *TicketAttachmentCreate {
	if v != nil {
		_c.SetFilename(*v)
	}
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *TicketAttachmentCreate) SetContentType(v string) *TicketAttachmentCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableContentType(v *string) *TicketAttachmentCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *TicketAttachmentCreate) SetSize(v int64) *TicketAttachmentCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableSize(v *int64) *TicketAttachmentCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *TicketAttachmentCreate) SetStorageKey(v string) *TicketAttachmentCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetContentID sets the "content_id" field.
func (_c *TicketAttachmentCreate) SetContentID(v string) *TicketAttachmentCreate {
	_c.mutation.SetContentID(v)
	return _c
}

// SetNillableContentID sets the "content_id" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableContentID(v *string) *TicketAttachmentCreate {
	if v != nil {
		_c.SetContentID(*v)
	}
	return _c
}

// SetInline sets the "inline" field.
func (_c *TicketAttachmentCreate) SetInline(v bool) *TicketAttachmentCreate {
	_c.mutation.SetInline(v)
	return _c
}

// SetNillableInline sets the "inline" field if the given value is not nil.
func (_c *TicketAttachmentCreate) SetNillableInline(v *bool) *TicketAttachmentCreate {
	if v != nil {
		_c.SetInline(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TicketAttachmentCreate) SetID(v string) *TicketAttachmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TicketAttachmentMutation object of the builder.
func (_c *TicketAttachmentCreate) Mutation() *TicketAttachmentMutation {
	return _c.mutation
}

// Save creates the TicketAttachment in the database.
func (_c *TicketAttachmentCreate) Save(ctx context.Context) (*TicketAttachment, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketAttachmentCreate) SaveX(ctx context.Context) *TicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketAttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketAttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketAttachmentCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := ticketattachment.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := ticketattachment.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.Inline(); !ok {
		v := ticketattachment.DefaultInline
		_c.mutation.SetInline(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketAttachmentCreate) check() error {
	if _, ok := _c.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "TicketAttachment.ticket_id"`)}
	}
	if v, ok := _c.mutation.TicketID(); ok {
		if err := ticketattachment.TicketIDValidator(v); err != nil {
			return &ValidationError{Name: "ticket_id", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.ticket_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "TicketAttachment.size"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "TicketAttachment.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := ticketattachment.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Inline(); !ok {
		return &ValidationError{Name: "inline", err: errors.New(`ent: missing required field "TicketAttachment.inline"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := ticketattachment.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TicketAttachment.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TicketAttachmentCreate) sqlSave(ctx context.Context) (*TicketAttachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected TicketAttachment.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketAttachmentCreate) createSpec() (*TicketAttachment, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketAttachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticketattachment.Table, sqlgraph.NewFieldSpec(ticketattachment.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(ticketattachment.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(ticketattachment.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(ticketattachment.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(ticketattachment.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.TicketID(); ok {
		_spec.SetField(ticketattachment.FieldTicketID, field.TypeString, value)
		_node.TicketID = value
	}
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(ticketattachment.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(ticketattachment.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(ticketattachment.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(ticketattachment.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.ContentID(); ok {
		_spec.SetField(ticketattachment.FieldContentID, field.TypeString, value)
		_node.ContentID = value
	}
	if value, ok := _c.mutation.Inline(); ok {
		_spec.SetField(ticketattachment.FieldInline, field.TypeBool, value)
		_node.Inline = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketAttachment.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketAttachmentUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketAttachmentCreate) OnConflict(opts ...sql.ConflictOption) *TicketAttachmentUpsertOne {
	_c.conflict = opts
	return &TicketAttachmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketAttachmentCreate) OnConflictColumns(columns ...string) *TicketAttachmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketAttachmentUpsertOne{
		create: _c,
	}
}

type (
	// TicketAttachmentUpsertOne is the builder for "upsert"-ing
	//  one TicketAttachment node.
	TicketAttachmentUpsertOne struct {
		create *TicketAttachmentCreate
	}

	// TicketAttachmentUpsert is the "OnConflict" setter.
	TicketAttachmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *TicketAttachmentUpsert) SetUpdateTime(v time.Time) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateUpdateTime() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *TicketAttachmentUpsert) ClearUpdateTime() *TicketAttachmentUpsert {
	u.SetNull(ticketattachment.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *TicketAttachmentUpsert) SetDeleteTime(v time.Time) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateDeleteTime() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *TicketAttachmentUpsert) ClearDeleteTime() *TicketAttachmentUpsert {
	u.SetNull(ticketattachment.FieldDeleteTime)
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketAttachmentUpsert) SetTicketID(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldTicketID, v)
	return u
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateTicketID() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldTicketID)
	return u
}

// SetFilename sets the "filename" field.
func (u *TicketAttachmentUpsert) SetFilename(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldFilename, v)
	return u
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateFilename() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldFilename)
	return u
}

// ClearFilename clears the value of the "filename" field.
func (u *TicketAttachmentUpsert) ClearFilename() *TicketAttachmentUpsert {
	u.SetNull(ticketattachment.FieldFilename)
	return u
}

// SetContentType sets the "content_type" field.
func (u *TicketAttachmentUpsert) SetContentType(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateContentType() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldContentType)
	return u
}

// ClearContentType clears the value of the "content_type" field.
func (u *TicketAttachmentUpsert) ClearContentType() *TicketAttachmentUpsert {
	u.SetNull(ticketattachment.FieldContentType)
	return u
}

// SetSize sets the "size" field.
func (u *TicketAttachmentUpsert) SetSize(v int64) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateSize() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldSize)
	return u
}

// AddSize adds v to the "size" field.
func (u *TicketAttachmentUpsert) AddSize(v int64) *TicketAttachmentUpsert {
	u.Add(ticketattachment.FieldSize, v)
	return u
}

// SetStorageKey sets the "storage_key" field.
func (u *TicketAttachmentUpsert) SetStorageKey(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateStorageKey() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldStorageKey)
	return u
}

// SetContentID sets the "content_id" field.
func (u *TicketAttachmentUpsert) SetContentID(v string) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldContentID, v)
	return u
}

// UpdateContentID sets the "content_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateContentID() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldContentID)
	return u
}

// ClearContentID clears the value of the "content_id" field.
func (u *TicketAttachmentUpsert) ClearContentID() *TicketAttachmentUpsert {
	u.SetNull(ticketattachment.FieldContentID)
	return u
}

// SetInline sets the "inline" field.
func (u *TicketAttachmentUpsert) SetInline(v bool) *TicketAttachmentUpsert {
	u.Set(ticketattachment.FieldInline, v)
	return u
}

// UpdateInline sets the "inline" field to the value that was provided on create.
func (u *TicketAttachmentUpsert) UpdateInline() *TicketAttachmentUpsert {
	u.SetExcluded(ticketattachment.FieldInline)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ticketattachment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketAttachmentUpsertOne) UpdateNewValues() *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ticketattachment.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(ticketattachment.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(ticketattachment.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketAttachmentUpsertOne) Ignore() *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketAttachmentUpsertOne) DoNothing() *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketAttachmentCreate.OnConflict
// documentation for more info.
func (u *TicketAttachmentUpsertOne) Update(set func(*TicketAttachmentUpsert)) *TicketAttachmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TicketAttachmentUpsertOne) SetUpdateTime(v time.Time) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateUpdateTime() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *TicketAttachmentUpsertOne) ClearUpdateTime() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *TicketAttachmentUpsertOne) SetDeleteTime(v time.Time) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateDeleteTime() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *TicketAttachmentUpsertOne) ClearDeleteTime() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearDeleteTime()
	})
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketAttachmentUpsertOne) SetTicketID(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateTicketID() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateTicketID()
	})
}

// SetFilename sets the "filename" field.
func (u *TicketAttachmentUpsertOne) SetFilename(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateFilename() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateFilename()
	})
}

// ClearFilename clears the value of the "filename" field.
func (u *TicketAttachmentUpsertOne) ClearFilename() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearFilename()
	})
}

// SetContentType sets the "content_type" field.
func (u *TicketAttachmentUpsertOne) SetContentType(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateContentType() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// ClearContentType clears the value of the "content_type" field.
func (u *TicketAttachmentUpsertOne) ClearContentType() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearContentType()
	})
}

// SetSize sets the "size" field.
func (u *TicketAttachmentUpsertOne) SetSize(v int64) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *TicketAttachmentUpsertOne) AddSize(v int64) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateSize() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateSize()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *TicketAttachmentUpsertOne) SetStorageKey(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateStorageKey() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetContentID sets the "content_id" field.
func (u *TicketAttachmentUpsertOne) SetContentID(v string) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetContentID(v)
	})
}

// UpdateContentID sets the "content_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateContentID() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateContentID()
	})
}

// ClearContentID clears the value of the "content_id" field.
func (u *TicketAttachmentUpsertOne) ClearContentID() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearContentID()
	})
}

// SetInline sets the "inline" field.
func (u *TicketAttachmentUpsertOne) SetInline(v bool) *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetInline(v)
	})
}

// UpdateInline sets the "inline" field to the value that was provided on create.
func (u *TicketAttachmentUpsertOne) UpdateInline() *TicketAttachmentUpsertOne {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateInline()
	})
}

// Exec executes the query.
func (u *TicketAttachmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketAttachmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketAttachmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketAttachmentUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TicketAttachmentUpsertOne.ID is not supported by MySQL driver. Use TicketAttachmentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketAttachmentUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketAttachmentCreateBulk is the builder for creating many TicketAttachment entities in bulk.
type TicketAttachmentCreateBulk struct {
	config
	err      error
	builders []*TicketAttachmentCreate
	conflict []sql.ConflictOption
}

// Save creates the TicketAttachment entities in the database.
func (_c *TicketAttachmentCreateBulk) Save(ctx context.Context) ([]*TicketAttachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketAttachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketAttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketAttachmentCreateBulk) SaveX(ctx context.Context) []*TicketAttachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketAttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketAttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TicketAttachment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketAttachmentUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketAttachmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketAttachmentUpsertBulk {
	_c.conflict = opts
	return &TicketAttachmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketAttachmentCreateBulk) OnConflictColumns(columns ...string) *TicketAttachmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketAttachmentUpsertBulk{
		create: _c,
	}
}

// TicketAttachmentUpsertBulk is the builder for "upsert"-ing
// a bulk of TicketAttachment nodes.
type TicketAttachmentUpsertBulk struct {
	create *TicketAttachmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ticketattachment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketAttachmentUpsertBulk) UpdateNewValues() *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ticketattachment.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(ticketattachment.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(ticketattachment.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TicketAttachment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketAttachmentUpsertBulk) Ignore() *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketAttachmentUpsertBulk) DoNothing() *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketAttachmentCreateBulk.OnConflict
// documentation for more info.
func (u *TicketAttachmentUpsertBulk) Update(set func(*TicketAttachmentUpsert)) *TicketAttachmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketAttachmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TicketAttachmentUpsertBulk) SetUpdateTime(v time.Time) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateUpdateTime() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *TicketAttachmentUpsertBulk) ClearUpdateTime() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *TicketAttachmentUpsertBulk) SetDeleteTime(v time.Time) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateDeleteTime() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *TicketAttachmentUpsertBulk) ClearDeleteTime() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearDeleteTime()
	})
}

// SetTicketID sets the "ticket_id" field.
func (u *TicketAttachmentUpsertBulk) SetTicketID(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateTicketID() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateTicketID()
	})
}

// SetFilename sets the "filename" field.
func (u *TicketAttachmentUpsertBulk) SetFilename(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateFilename() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateFilename()
	})
}

// ClearFilename clears the value of the "filename" field.
func (u *TicketAttachmentUpsertBulk) ClearFilename() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearFilename()
	})
}

// SetContentType sets the "content_type" field.
func (u *TicketAttachmentUpsertBulk) SetContentType(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateContentType() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateContentType()
	})
}

// ClearContentType clears the value of the "content_type" field.
func (u *TicketAttachmentUpsertBulk) ClearContentType() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearContentType()
	})
}

// SetSize sets the "size" field.
func (u *TicketAttachmentUpsertBulk) SetSize(v int64) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetSize(v)
	})
}

// AddSize adds v to the "size" field.
func (u *TicketAttachmentUpsertBulk) AddSize(v int64) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.AddSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateSize() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateSize()
	})
}

// SetStorageKey sets the "storage_key" field.
func (u *TicketAttachmentUpsertBulk) SetStorageKey(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storage_key" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateStorageKey() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateStorageKey()
	})
}

// SetContentID sets the "content_id" field.
func (u *TicketAttachmentUpsertBulk) SetContentID(v string) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetContentID(v)
	})
}

// UpdateContentID sets the "content_id" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateContentID() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateContentID()
	})
}

// ClearContentID clears the value of the "content_id" field.
func (u *TicketAttachmentUpsertBulk) ClearContentID() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.ClearContentID()
	})
}

// SetInline sets the "inline" field.
func (u *TicketAttachmentUpsertBulk) SetInline(v bool) *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.SetInline(v)
	})
}

// UpdateInline sets the "inline" field to the value that was provided on create.
func (u *TicketAttachmentUpsertBulk) UpdateInline() *TicketAttachmentUpsertBulk {
	return u.Update(func(s *TicketAttachmentUpsert) {
		s.UpdateInline()
	})
}

// Exec executes the query.
func (u *TicketAttachmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketAttachmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketAttachmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketAttachmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
