// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticket"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/ticketcomment"
)

// TicketComment is the model entity for the TicketComment schema.
type TicketComment struct {
	config `json:"-"`
	// ID of the ent.
	// UUID primary key
	ID string `json:"id,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Owning ticket UUID
	TicketID string `json:"ticket_id,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Internal note (agents only) vs public reply
	Internal bool `json:"internal,omitempty"`
	// Internal user author (0 if external)
	AuthorID uint32 `json:"author_id,omitempty"`
	// External requester email when the reply came by mail
	AuthorEmail string `json:"author_email,omitempty"`
	// RFC822 Message-Id this comment was sent/received as (for threading)
	MessageID string `json:"message_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketCommentQuery when eager-loading is set.
	Edges        TicketCommentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketCommentEdges holds the relations/edges for other nodes in the graph.
type TicketCommentEdges struct {
	// Ticket holds the value of the ticket edge.
	Ticket *Ticket `json:"ticket,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketCommentEdges) TicketOrErr() (*Ticket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TicketComment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticketcomment.FieldInternal:
			values[i] = new(sql.NullBool)
		case ticketcomment.FieldTenantID, ticketcomment.FieldAuthorID:
			values[i] = new(sql.NullInt64)
		case ticketcomment.FieldID, ticketcomment.FieldTicketID, ticketcomment.FieldBody, ticketcomment.FieldAuthorEmail, ticketcomment.FieldMessageID:
			values[i] = new(sql.NullString)
		case ticketcomment.FieldCreateTime, ticketcomment.FieldUpdateTime, ticketcomment.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TicketComment fields.
func (_m *TicketComment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticketcomment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case ticketcomment.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case ticketcomment.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case ticketcomment.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case ticketcomment.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case ticketcomment.FieldTicketID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = value.String
			}
		case ticketcomment.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case ticketcomment.FieldInternal:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field internal", values[i])
			} else if value.Valid {
				_m.Internal = value.Bool
			}
		case ticketcomment.FieldAuthorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field author_id", values[i])
			} else if value.Valid {
				_m.AuthorID = uint32(value.Int64)
			}
		case ticketcomment.FieldAuthorEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author_email", values[i])
			} else if value.Valid {
				_m.AuthorEmail = value.String
			}
		case ticketcomment.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TicketComment.
// This includes values selected through modifiers, order, etc.
func (_m *TicketComment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicket queries the "ticket" edge of the TicketComment entity.
func (_m *TicketComment) QueryTicket() *TicketQuery {
	return NewTicketCommentClient(_m.config).QueryTicket(_m)
}

// Update returns a builder for updating this TicketComment.
// Note that you need to call TicketComment.Unwrap() before calling this method if this TicketComment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TicketComment) Update() *TicketCommentUpdateOne {
	return NewTicketCommentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TicketComment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TicketComment) Unwrap() *TicketComment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TicketComment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TicketComment) String() string {
	var builder strings.Builder
	builder.WriteString("TicketComment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("ticket_id=")
	builder.WriteString(_m.TicketID)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("internal=")
	builder.WriteString(fmt.Sprintf("%v", _m.Internal))
	builder.WriteString(", ")
	builder.WriteString("author_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthorID))
	builder.WriteString(", ")
	builder.WriteString("author_email=")
	builder.WriteString(_m.AuthorEmail)
	builder.WriteString(", ")
	builder.WriteString("message_id=")
	builder.WriteString(_m.MessageID)
	builder.WriteByte(')')
	return builder.String()
}

// TicketComments is a parsable slice of TicketComment.
type TicketComments []*TicketComment
