// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// TicketAttachment is the predicate function for ticketattachment builders.
type TicketAttachment func(*sql.Selector)

// TicketComment is the predicate function for ticketcomment builders.
type TicketComment func(*sql.Selector)
