// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TicketTicketsColumns holds the columns for the "ticket_tickets" table.
	TicketTicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "external_id", Type: field.TypeString, Nullable: true, Comment: "iris/RFC822 Message-Id for dedup"},
		{Name: "subject", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeString, Comment: "Lifecycle status", Default: "TICKET_STATUS_OPEN"},
		{Name: "priority", Type: field.TypeString, Default: "TICKET_PRIORITY_NORMAL"},
		{Name: "source", Type: field.TypeString, Comment: "Origin: iris, manual", Default: "manual"},
		{Name: "requester_email", Type: field.TypeString, Nullable: true},
		{Name: "requester_name", Type: field.TypeString, Nullable: true},
		{Name: "recipient", Type: field.TypeString, Nullable: true, Comment: "Support address the mail was delivered to"},
		{Name: "assignee_id", Type: field.TypeUint32, Comment: "Internal user the ticket is assigned to (0 = unassigned)", Default: 0},
	}
	// TicketTicketsTable holds the schema information for the "ticket_tickets" table.
	TicketTicketsTable = &schema.Table{
		Name:       "ticket_tickets",
		Columns:    TicketTicketsColumns,
		PrimaryKey: []*schema.Column{TicketTicketsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ticket_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{TicketTicketsColumns[5]},
			},
			{
				Name:    "ticket_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{TicketTicketsColumns[5], TicketTicketsColumns[9]},
			},
			{
				Name:    "ticket_tenant_id_assignee_id",
				Unique:  false,
				Columns: []*schema.Column{TicketTicketsColumns[5], TicketTicketsColumns[15]},
			},
			{
				Name:    "ticket_tenant_id_external_id",
				Unique:  true,
				Columns: []*schema.Column{TicketTicketsColumns[5], TicketTicketsColumns[6]},
			},
		},
	}
	// TicketCommentsColumns holds the columns for the "ticket_comments" table.
	TicketCommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "body", Type: field.TypeString, Size: 2147483647},
		{Name: "internal", Type: field.TypeBool, Comment: "Internal note (agents only) vs public reply", Default: false},
		{Name: "author_id", Type: field.TypeUint32, Comment: "Internal user author (0 if external)", Default: 0},
		{Name: "author_email", Type: field.TypeString, Nullable: true, Comment: "External requester email when the reply came by mail"},
		{Name: "ticket_id", Type: field.TypeString, Comment: "Owning ticket UUID"},
	}
	// TicketCommentsTable holds the schema information for the "ticket_comments" table.
	TicketCommentsTable = &schema.Table{
		Name:       "ticket_comments",
		Columns:    TicketCommentsColumns,
		PrimaryKey: []*schema.Column{TicketCommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ticket_comments_ticket_tickets_comments",
				Columns:    []*schema.Column{TicketCommentsColumns[9]},
				RefColumns: []*schema.Column{TicketTicketsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "ticketcomment_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{TicketCommentsColumns[4]},
			},
			{
				Name:    "ticketcomment_ticket_id",
				Unique:  false,
				Columns: []*schema.Column{TicketCommentsColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TicketTicketsTable,
		TicketCommentsTable,
	}
)

func init() {
	TicketTicketsTable.Annotation = &entsql.Annotation{
		Table: "ticket_tickets",
	}
	TicketCommentsTable.ForeignKeys[0].RefTable = TicketTicketsTable
	TicketCommentsTable.Annotation = &entsql.Annotation{
		Table: "ticket_comments",
	}
}
