// Code generated by ent, DO NOT EDIT.

package ticketcomment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/go-tangra/go-tangra-ticket/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldTenantID, v))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldTicketID, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldBody, v))
}

// Internal applies equality check predicate on the "internal" field. It's identical to InternalEQ.
func Internal(v bool) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldInternal, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorEmail applies equality check predicate on the "author_email" field. It's identical to AuthorEmailEQ.
func AuthorEmail(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldAuthorEmail, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotNull(FieldTenantID))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotIn(FieldTicketID, vs...))
}

// TicketIDGT applies the GT predicate on the "ticket_id" field.
func TicketIDGT(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGT(FieldTicketID, v))
}

// TicketIDGTE applies the GTE predicate on the "ticket_id" field.
func TicketIDGTE(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGTE(FieldTicketID, v))
}

// TicketIDLT applies the LT predicate on the "ticket_id" field.
func TicketIDLT(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLT(FieldTicketID, v))
}

// TicketIDLTE applies the LTE predicate on the "ticket_id" field.
func TicketIDLTE(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLTE(FieldTicketID, v))
}

// TicketIDContains applies the Contains predicate on the "ticket_id" field.
func TicketIDContains(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldContains(FieldTicketID, v))
}

// TicketIDHasPrefix applies the HasPrefix predicate on the "ticket_id" field.
func TicketIDHasPrefix(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldHasPrefix(FieldTicketID, v))
}

// TicketIDHasSuffix applies the HasSuffix predicate on the "ticket_id" field.
func TicketIDHasSuffix(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldHasSuffix(FieldTicketID, v))
}

// TicketIDEqualFold applies the EqualFold predicate on the "ticket_id" field.
func TicketIDEqualFold(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEqualFold(FieldTicketID, v))
}

// TicketIDContainsFold applies the ContainsFold predicate on the "ticket_id" field.
func TicketIDContainsFold(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldContainsFold(FieldTicketID, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldContainsFold(FieldBody, v))
}

// InternalEQ applies the EQ predicate on the "internal" field.
func InternalEQ(v bool) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldInternal, v))
}

// InternalNEQ applies the NEQ predicate on the "internal" field.
func InternalNEQ(v bool) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldInternal, v))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorIDGT applies the GT predicate on the "author_id" field.
func AuthorIDGT(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGT(FieldAuthorID, v))
}

// AuthorIDGTE applies the GTE predicate on the "author_id" field.
func AuthorIDGTE(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGTE(FieldAuthorID, v))
}

// AuthorIDLT applies the LT predicate on the "author_id" field.
func AuthorIDLT(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLT(FieldAuthorID, v))
}

// AuthorIDLTE applies the LTE predicate on the "author_id" field.
func AuthorIDLTE(v uint32) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLTE(FieldAuthorID, v))
}

// AuthorEmailEQ applies the EQ predicate on the "author_email" field.
func AuthorEmailEQ(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEQ(FieldAuthorEmail, v))
}

// AuthorEmailNEQ applies the NEQ predicate on the "author_email" field.
func AuthorEmailNEQ(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNEQ(FieldAuthorEmail, v))
}

// AuthorEmailIn applies the In predicate on the "author_email" field.
func AuthorEmailIn(vs ...string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIn(FieldAuthorEmail, vs...))
}

// AuthorEmailNotIn applies the NotIn predicate on the "author_email" field.
func AuthorEmailNotIn(vs ...string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotIn(FieldAuthorEmail, vs...))
}

// AuthorEmailGT applies the GT predicate on the "author_email" field.
func AuthorEmailGT(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGT(FieldAuthorEmail, v))
}

// AuthorEmailGTE applies the GTE predicate on the "author_email" field.
func AuthorEmailGTE(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldGTE(FieldAuthorEmail, v))
}

// AuthorEmailLT applies the LT predicate on the "author_email" field.
func AuthorEmailLT(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLT(FieldAuthorEmail, v))
}

// AuthorEmailLTE applies the LTE predicate on the "author_email" field.
func AuthorEmailLTE(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldLTE(FieldAuthorEmail, v))
}

// AuthorEmailContains applies the Contains predicate on the "author_email" field.
func AuthorEmailContains(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldContains(FieldAuthorEmail, v))
}

// AuthorEmailHasPrefix applies the HasPrefix predicate on the "author_email" field.
func AuthorEmailHasPrefix(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldHasPrefix(FieldAuthorEmail, v))
}

// AuthorEmailHasSuffix applies the HasSuffix predicate on the "author_email" field.
func AuthorEmailHasSuffix(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldHasSuffix(FieldAuthorEmail, v))
}

// AuthorEmailIsNil applies the IsNil predicate on the "author_email" field.
func AuthorEmailIsNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldIsNull(FieldAuthorEmail))
}

// AuthorEmailNotNil applies the NotNil predicate on the "author_email" field.
func AuthorEmailNotNil() predicate.TicketComment {
	return predicate.TicketComment(sql.FieldNotNull(FieldAuthorEmail))
}

// AuthorEmailEqualFold applies the EqualFold predicate on the "author_email" field.
func AuthorEmailEqualFold(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldEqualFold(FieldAuthorEmail, v))
}

// AuthorEmailContainsFold applies the ContainsFold predicate on the "author_email" field.
func AuthorEmailContainsFold(v string) predicate.TicketComment {
	return predicate.TicketComment(sql.FieldContainsFold(FieldAuthorEmail, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.TicketComment {
	return predicate.TicketComment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.Ticket) predicate.TicketComment {
	return predicate.TicketComment(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketComment) predicate.TicketComment {
	return predicate.TicketComment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketComment) predicate.TicketComment {
	return predicate.TicketComment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketComment) predicate.TicketComment {
	return predicate.TicketComment(sql.NotPredicates(p))
}
