// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-ticket/internal/cert"
	"github.com/go-tangra/go-tangra-ticket/internal/client"
	"github.com/go-tangra/go-tangra-ticket/internal/data"
	"github.com/go-tangra/go-tangra-ticket/internal/metrics"
	"github.com/go-tangra/go-tangra-ticket/internal/server"
	"github.com/go-tangra/go-tangra-ticket/internal/service"
	"github.com/go-tangra/go-tangra-ticket/internal/webhook"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	ticketRepo := data.NewTicketRepo(context, entClient)
	collector := metrics.NewCollector(context)
	ticketService := service.NewTicketService(context, ticketRepo, collector)
	commentRepo := data.NewCommentRepo(context, entClient)
	commentService := service.NewCommentService(context, commentRepo, ticketRepo)
	adminClient, cleanup2, err := client.NewAdminClient(context, certManager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userService := service.NewUserService(context, adminClient)
	grpcServer := server.NewGRPCServer(context, certManager, ticketService, commentService, userService)
	irisHandler := webhook.NewIrisHandler(context, ticketRepo, collector)
	httpServer := server.NewHTTPServer(context, irisHandler)
	registrationClient, err := data.NewRegistrationClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := newApp(context, grpcServer, httpServer, registrationClient)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
