// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-ticket/internal/cert"
	"github.com/go-tangra/go-tangra-ticket/internal/client"
	"github.com/go-tangra/go-tangra-ticket/internal/data"
	"github.com/go-tangra/go-tangra-ticket/internal/mailer"
	"github.com/go-tangra/go-tangra-ticket/internal/metrics"
	"github.com/go-tangra/go-tangra-ticket/internal/rules"
	"github.com/go-tangra/go-tangra-ticket/internal/server"
	"github.com/go-tangra/go-tangra-ticket/internal/service"
	"github.com/go-tangra/go-tangra-ticket/internal/webhook"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	ticketRepo := data.NewTicketRepo(context, entClient)
	attachmentRepo := data.NewAttachmentRepo(context, entClient)
	collector := metrics.NewCollector(context)
	ticketService := service.NewTicketService(context, ticketRepo, attachmentRepo, collector)
	commentRepo := data.NewCommentRepo(context, entClient)
	mailerMailer := mailer.NewMailer(context)
	commentService := service.NewCommentService(context, commentRepo, ticketRepo, mailerMailer)
	adminClient, cleanup2, err := client.NewAdminClient(context, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userService := service.NewUserService(context, adminClient)
	tagRepo := data.NewTagRepo(context, entClient)
	tagService := service.NewTagService(context, tagRepo, ticketRepo)
	ruleRepo := data.NewRuleRepo(context, entClient)
	engine, err := rules.NewEngine()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ruleService := service.NewRuleService(context, ruleRepo, engine)
	grpcServer := server.NewGRPCServer(context, v, ticketService, commentService, userService, tagService, ruleService)
	storageClient, cleanup3, err := data.NewStorageClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	irisHandler := webhook.NewIrisHandler(context, ticketRepo, commentRepo, attachmentRepo, storageClient, tagRepo, ruleRepo, engine, mailerMailer, collector)
	httpServer := server.NewHTTPServer(context, irisHandler, attachmentRepo, storageClient)
	registrationClient, err := data.NewRegistrationClient(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := newApp(context, grpcServer, httpServer, registrationClient)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
